package GUI;

import DAO.DAO_TaiKhoan;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class frm_Main extends javax.swing.JFrame {

    private JPanel childPanel;
    /**
     * Creates new form frm_Main
     */
    String maTaiKhoan = "";

    public frm_Main() {
        if (maTaiKhoan.equals("")) {
            frm_DangNhap jf = new frm_DangNhap();
            jf.show();
        } else {
            this.setUndecorated(false);                 //false for title bar. True for no title bar
            this.setAlwaysOnTop(true);
            this.setResizable(true);
            this.setVisible(true);
            initComponents();
            Toolkit a = Toolkit.getDefaultToolkit();
            int xSize = (int) a.getScreenSize().getWidth();
            int ySize = (int) a.getScreenSize().getHeight();
            this.setSize(xSize, ySize);
        }

    }

    public frm_Main(String _ma) {
        this.maTaiKhoan = _ma;
        this.setUndecorated(false);                 //false for title bar. True for no title bar
        this.setAlwaysOnTop(true);
        this.setResizable(true);
        this.setVisible(true);
        initComponents();
        Toolkit a = Toolkit.getDefaultToolkit();
        int xSize = (int) a.getScreenSize().getWidth();
        int ySize = (int) a.getScreenSize().getHeight();
        this.setSize(xSize, ySize);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_logo = new javax.swing.JLabel();
        btn_SanPham = new javax.swing.JLabel();
        btn_BanSach = new javax.swing.JLabel();
        btn_KhoHang = new javax.swing.JLabel();
        btn_HoaDon = new javax.swing.JLabel();
        btn_ThongKe = new javax.swing.JLabel();
        btn_ThanhVien = new javax.swing.JLabel();
        btn_DangXuat = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JLabel();
        btn_UuDai = new javax.swing.JLabel();
        btn_HeThongVatTu = new javax.swing.JLabel();
        btn_TaiKhoan = new javax.swing.JLabel();
        panel_Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        btn_SanPham.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_SanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N
        btn_SanPham.setText("   Quản lý sản phẩm");
        btn_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SanPhamMouseClicked(evt);
            }
        });

        btn_BanSach.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_BanSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        btn_BanSach.setText("   Quản lý bán sách");
        btn_BanSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BanSachMouseClicked(evt);
            }
        });

        btn_KhoHang.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_KhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse.png"))); // NOI18N
        btn_KhoHang.setText("   Quản lý kho hàng");
        btn_KhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_KhoHangMouseClicked(evt);
            }
        });

        btn_HoaDon.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        btn_HoaDon.setText("   Quản lý hóa đơn");
        btn_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HoaDonMouseClicked(evt);
            }
        });

        btn_ThongKe.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/analytics.png"))); // NOI18N
        btn_ThongKe.setText("   Thống kê");
        btn_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongKeMouseClicked(evt);
            }
        });

        btn_ThanhVien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_ThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/members.png"))); // NOI18N
        btn_ThanhVien.setText("   Quản lý thành viên");
        btn_ThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThanhVienMouseClicked(evt);
            }
        });

        btn_DangXuat.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_DangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btn_DangXuat.setText("   Đăng xuất");
        btn_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DangXuatMouseClicked(evt);
            }
        });

        btn_TimKiem.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seo.png"))); // NOI18N
        btn_TimKiem.setText("   Tìm kiếm sản phẩm");
        btn_TimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimKiemMouseClicked(evt);
            }
        });

        btn_UuDai.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_UuDai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coupon.png"))); // NOI18N
        btn_UuDai.setText("   Quản lý ưu đãi");
        btn_UuDai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UuDaiMouseClicked(evt);
            }
        });

        btn_HeThongVatTu.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_HeThongVatTu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/systemsetting.png"))); // NOI18N
        btn_HeThongVatTu.setText("   Hệ thống, vật tư");
        btn_HeThongVatTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HeThongVatTuMouseClicked(evt);
            }
        });

        btn_TaiKhoan.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account.png"))); // NOI18N
        btn_TaiKhoan.setText("   Quản lý tài khoản");
        btn_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaiKhoanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_UuDai, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_KhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(img_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_BanSach, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_HeThongVatTu, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_TaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(img_logo)
                .addGap(30, 30, 30)
                .addComponent(btn_BanSach, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_UuDai, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_KhoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_HeThongVatTu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_Main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcom.png"))); // NOI18N

        javax.swing.GroupLayout panel_MainLayout = new javax.swing.GroupLayout(panel_Main);
        panel_Main.setLayout(panel_MainLayout);
        panel_MainLayout.setHorizontalGroup(
            panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MainLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
                .addGap(1426, 1426, 1426))
        );
        panel_MainLayout.setVerticalGroup(
            panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MainLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BanSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BanSachMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_BanSach(maTaiKhoan);
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_BanSach);
    }//GEN-LAST:event_btn_BanSachMouseClicked

    private void btn_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SanPhamMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_QLSanPham();
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_SanPham);
    }//GEN-LAST:event_btn_SanPhamMouseClicked

    private void btn_TimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimKiemMouseClicked
        // TODO add your handling code here:
        setColor(btn_TimKiem);
        childPanel = new panel_TimKiemSP();
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
    }//GEN-LAST:event_btn_TimKiemMouseClicked

    private void btn_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HoaDonMouseClicked
        // TODO add your handling code here:
        childPanel = new penel_QLHoaDon();
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_HoaDon);
    }//GEN-LAST:event_btn_HoaDonMouseClicked

    private void btn_ThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThanhVienMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_QLThanhVien(DAO_TaiKhoan.getMaQuyenfromMaTK(maTaiKhoan));
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_ThanhVien);
    }//GEN-LAST:event_btn_ThanhVienMouseClicked

    private void btn_UuDaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UuDaiMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_QLUuDai(DAO_TaiKhoan.getMaQuyenfromMaTK(maTaiKhoan));
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_UuDai);
    }//GEN-LAST:event_btn_UuDaiMouseClicked

    private void btn_KhoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_KhoHangMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_QLKhoHang(maTaiKhoan);
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_KhoHang);
    }//GEN-LAST:event_btn_KhoHangMouseClicked

    private void btn_HeThongVatTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HeThongVatTuMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_QLHeThongVatTu();
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_HeThongVatTu);
    }//GEN-LAST:event_btn_HeThongVatTuMouseClicked

    private void btn_ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongKeMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_ThongKe(DAO_TaiKhoan.getMaQuyenfromMaTK(maTaiKhoan));
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_ThongKe);
    }//GEN-LAST:event_btn_ThongKeMouseClicked

    private void btn_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaiKhoanMouseClicked
        // TODO add your handling code here:
        childPanel = new panel_QLTaiKhoan(maTaiKhoan);
        panel_Main.removeAll();
        panel_Main.setLayout(new BorderLayout());
        panel_Main.add(childPanel);
        panel_Main.validate();
        panel_Main.repaint();
        setColor(btn_TaiKhoan);
    }//GEN-LAST:event_btn_TaiKhoanMouseClicked

    private void btn_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DangXuatMouseClicked
        // TODO add your handling code here:
        int d = JOptionPane.showConfirmDialog(this, "Bạn có muốn Đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (d == JOptionPane.YES_OPTION) {
            this.hide();
            frm_DangNhap jf = new frm_DangNhap();
            jf.show();
        } else
            return;
    }//GEN-LAST:event_btn_DangXuatMouseClicked

    public void changeColor(JLabel lable, Color textcolor, Color backgroundcolor) {
        lable.setForeground(textcolor);
        lable.setOpaque(true);
        lable.setBackground(backgroundcolor);
    }

    public void setColor(JLabel lbl) {
        JLabel[] arr = new JLabel[]{btn_BanSach, btn_HoaDon, btn_KhoHang, btn_SanPham, btn_HeThongVatTu, btn_ThanhVien, btn_ThongKe, btn_TimKiem, btn_UuDai, btn_TaiKhoan};
        for (JLabel i : arr) {
            if (i.getText().equals(lbl.getText())) {
                changeColor(i, Color.BLACK, Color.decode("#eeecec"));
            } else {
                changeColor(i, Color.BLACK, Color.WHITE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_BanSach;
    private javax.swing.JLabel btn_DangXuat;
    private javax.swing.JLabel btn_HeThongVatTu;
    private javax.swing.JLabel btn_HoaDon;
    private javax.swing.JLabel btn_KhoHang;
    private javax.swing.JLabel btn_SanPham;
    private javax.swing.JLabel btn_TaiKhoan;
    private javax.swing.JLabel btn_ThanhVien;
    private javax.swing.JLabel btn_ThongKe;
    private javax.swing.JLabel btn_TimKiem;
    private javax.swing.JLabel btn_UuDai;
    private javax.swing.JLabel img_logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_Main;
    // End of variables declaration//GEN-END:variables
}
