package GUI;

import DAO.DAO_LoaiThanhVien;
import DAO.DAO_ThanhVien;
import DTO.DTO_LoaiThanhVien;
import DTO.DTO_Sach;
import DTO.DTO_ThanhVien;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.jws.WebParam;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ChauCuteVCL
 */
public class panel_QLThanhVien extends javax.swing.JPanel {

    DAO_LoaiThanhVien daoLTV = new DAO_LoaiThanhVien();
    DAO_ThanhVien daoTV = new DAO_ThanhVien();
    DefaultTableModel model_LTV = new DefaultTableModel();
    DefaultTableModel model_TV = new DefaultTableModel();
    Vector tblTitle = new Vector();
    Vector tblTitleLTV = new Vector();
    /**
     * Creates new form panel_QLThanhVien
     */
    public panel_QLThanhVien(String maQ) {
        initComponents();
        loadTitle();
        loadTitleLTV();
        loadDS();
        loadCB_LoaiTV();
        if(maQ.trim().equals("user"))
            phanquyen();
        else
            loadDS_LTV();
        
        
    }
   
    public void loadDS_LTV()
    {
        model_LTV = new DefaultTableModel();
        model_LTV.setColumnIdentifiers(tblTitleLTV);
        List<DTO_LoaiThanhVien> lst = DAO_LoaiThanhVien.getDS_LoaiThanhVien();
        for(DTO_LoaiThanhVien i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaLoaiTV);
            a.add(i.TenLoaiTV);
            a.add(i.TienCanDat);
            a.add(i.PhanTramGiamGia);
           model_LTV.addRow(a);
        }
        table_DS_LTV.setModel(model_LTV);
    }
    public void loadTitle()
    {
        tblTitle.add("Mã thành viên");
        tblTitle.add("Tên thành viên"); 
        tblTitle.add("SĐT");
        tblTitle.add("Tiền đã mua");
        tblTitle.add("Mã loại TV"); 
    }
    
    public void loadTitleLTV()
    {
        tblTitleLTV.add("Mã loại TV");
        tblTitleLTV.add("Tên loại TV"); 
        tblTitleLTV.add("Tiền cần đạt");
        tblTitleLTV.add("% giảm giá");
    }
    public void loadDS()
    {
        model_TV = new DefaultTableModel();
        model_TV.setColumnIdentifiers(tblTitle);
       List<DTO_ThanhVien> lst = DAO_ThanhVien.getDS_ThanhVien();
        for(DTO_ThanhVien i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaTV);
            a.add(i.TenThanhVien);
            a.add(i.SDT);
            a.add(i.TienDaMua);
            a.add(i.MaLoaiTV);
            model_TV.addRow(a);
        }
        table_DSTV.setModel(model_TV);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_MaTV_TC = new javax.swing.JTextField();
        txt_SDT_TV_TC = new javax.swing.JTextField();
        btn_TraCuu = new javax.swing.JButton();
        btn_LamMoi_TC = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_KQTraCuu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_MaTV = new javax.swing.JTextField();
        txt_TenTV = new javax.swing.JTextField();
        txt_TienDaMua = new javax.swing.JTextField();
        btn_ThemTV = new javax.swing.JButton();
        btn_SuaTV = new javax.swing.JButton();
        btn_XoaTV = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        txt_SDT_TV = new javax.swing.JTextField();
        cbb_LoaiTV = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DSTV = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_DS_LTV = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_MaLTV = new javax.swing.JTextField();
        txt_TenLTV = new javax.swing.JTextField();
        txt_TienCanDatLTV = new javax.swing.JTextField();
        txt_PTGG_LTV = new javax.swing.JTextField();
        btn_ThemLTV = new javax.swing.JButton();
        btn_SuaLTV = new javax.swing.JButton();
        btn_XoaLTV = new javax.swing.JButton();
        btn_LamMoi_LTV = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Tra cứu thành viên:");
        jLabel3.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Mã thành viên:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("SDT thành viên:");

        txt_MaTV_TC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_SDT_TV_TC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SDT_TV_TC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SDT_TV_TCKeyTyped(evt);
            }
        });

        btn_TraCuu.setBackground(new java.awt.Color(102, 153, 255));
        btn_TraCuu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkTT.png"))); // NOI18N
        btn_TraCuu.setText("Tra cứu thành viên");
        btn_TraCuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TraCuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TraCuuMouseClicked(evt);
            }
        });
        btn_TraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraCuuActionPerformed(evt);
            }
        });

        btn_LamMoi_TC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LamMoi_TC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_TC.setText("Làm mới");
        btn_LamMoi_TC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_LamMoi_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_TCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_LamMoi_TC, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_TraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_SDT_TV_TC)
                            .addComponent(txt_MaTV_TC))))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaTV_TC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SDT_TV_TC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Kết quả tìm kiếm:");
        jLabel6.setToolTipText("");

        table_KQTraCuu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_KQTraCuu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_KQTraCuu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_KQTraCuu.setRowHeight(35);
        jScrollPane2.setViewportView(table_KQTraCuu);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Thông tin thành viên:");
        jLabel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Mã thành viên:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Tên thành viên:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Số điện thoại:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Loại thành viên:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Số tiền đã mua:");

        txt_MaTV.setEditable(false);
        txt_MaTV.setBackground(new java.awt.Color(234, 234, 234));
        txt_MaTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_MaTV.setText("Automatic...");

        txt_TenTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TienDaMua.setEditable(false);
        txt_TienDaMua.setBackground(new java.awt.Color(234, 234, 234));
        txt_TienDaMua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_ThemTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemTV.setText("Thêm thành viên");
        btn_ThemTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemTV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemTVActionPerformed(evt);
            }
        });

        btn_SuaTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaTV.setText("Sửa thành viên");
        btn_SuaTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaTVActionPerformed(evt);
            }
        });

        btn_XoaTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaTV.setText("Xóa thành viên");
        btn_XoaTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTVActionPerformed(evt);
            }
        });

        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi.setText("    Làm mới");
        btn_LamMoi.setActionCommand("Làm mới");
        btn_LamMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        txt_SDT_TV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SDT_TV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SDT_TVKeyTyped(evt);
            }
        });

        cbb_LoaiTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_LoaiTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_LoaiTV.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21))
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_SDT_TV)
                                    .addComponent(txt_TenTV)
                                    .addComponent(txt_MaTV)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_TienDaMua)
                                            .addComponent(cbb_LoaiTV, 0, 268, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btn_ThemTV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(btn_SuaTV)
                                .addGap(28, 28, 28)
                                .addComponent(btn_XoaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_SDT_TV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_TenTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_TienDaMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbb_LoaiTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemTV)
                    .addComponent(btn_SuaTV)
                    .addComponent(btn_XoaTV)
                    .addComponent(btn_LamMoi))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        table_DSTV.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DSTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DSTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_DSTV.setRowHeight(35);
        table_DSTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_DSTV);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Quản lý loại thành viên:");
        jLabel7.setToolTipText("");

        table_DS_LTV.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DS_LTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DS_LTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_DS_LTV.setRowHeight(35);
        table_DS_LTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DS_LTVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_DS_LTV);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Mã loại thành viên:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Tên loại thành viên:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Tiền cần đạt:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Phần trăm giảm:");

        txt_MaLTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TenLTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TienCanDatLTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TienCanDatLTV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PTGG_LTVKeyTyped(evt);
            }
        });

        txt_PTGG_LTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_PTGG_LTV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PTGG_LTVKeyTyped1(evt);
            }
        });

        btn_ThemLTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemLTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemLTV.setText("Thêm LTV");
        btn_ThemLTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemLTV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemLTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLTVActionPerformed(evt);
            }
        });

        btn_SuaLTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaLTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaLTV.setText("Sửa LTV");
        btn_SuaLTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaLTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLTVActionPerformed(evt);
            }
        });

        btn_XoaLTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaLTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaLTV.setText("Xóa LTV");
        btn_XoaLTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaLTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLTVActionPerformed(evt);
            }
        });

        btn_LamMoi_LTV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi_LTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_LTV.setText(" Làm mới");
        btn_LamMoi_LTV.setActionCommand("Làm mới");
        btn_LamMoi_LTV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi_LTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_LTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(44, 546, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel26)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel25)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_PTGG_LTV, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txt_TienCanDatLTV, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_TenLTV, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaLTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_SuaLTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_XoaLTV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_LamMoi_LTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ThemLTV))
                        .addGap(42, 42, 42))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_MaLTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TenLTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TienCanDatLTV)
                            .addComponent(jLabel25))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_PTGG_LTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(btn_ThemLTV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SuaLTV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaLTV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_LamMoi_LTV)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_DSTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSTVMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = table_DSTV.rowAtPoint(p);
        String matv = (String)model_TV.getValueAt(row, 0).toString();
        String tentv = (String)model_TV.getValueAt(row, 1).toString();
        String sdt = (String)model_TV.getValueAt(row, 2).toString();
        String tiendamua = (String)model_TV.getValueAt(row, 3).toString();
        String maloaitv=(String)model_TV.getValueAt(row, 4).toString();
        
        txt_MaTV.setText(matv);
        txt_TenTV.setText(tentv);
        txt_SDT_TV.setText(sdt);
        txt_TienDaMua.setText(tiendamua);
        cbb_LoaiTV.setSelectedItem(daoLTV.getTenLTV_fromMaLTV(maloaitv));
    }//GEN-LAST:event_table_DSTVMouseClicked

    
    
    private void btn_TraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraCuuActionPerformed

        if(txt_MaTV_TC.getText().trim().equals("") && txt_SDT_TV_TC.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Hãy điền thông tin mã thành viên hoặc số điện thoại thành viên!","Thông báo",JOptionPane.YES_OPTION);
        }
        else{
   
            
            if(!txt_MaTV_TC.getText().trim().equals(""))
            {
                if(daoTV.checkMembers_MaTV(txt_MaTV_TC.getText().trim()))
                {
                   DTO_ThanhVien tv = daoTV.getThanhVien_from_MaTV(txt_MaTV_TC.getText().trim());
                   Vector a = new Vector();
                   Vector _dt = new Vector();
                   a.add(tv.MaTV);
                   a.add(tv.TenThanhVien);
                   a.add(tv.SDT);
                   a.add(tv.TienDaMua);
                   a.add(tv.MaLoaiTV);
                   _dt.add(a);
                   table_KQTraCuu.setModel(new DefaultTableModel(_dt,tblTitle));
                }
                else
                    JOptionPane.showMessageDialog(this, "Mã thành viên không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
            }else if(!txt_SDT_TV_TC.getText().trim().equals(""))
            {
                
             if(daoTV.checkMembers_SDT(txt_SDT_TV_TC.getText().trim()))
                {
               DTO_ThanhVien tv = daoTV.getThanhVien_from_SDT(txt_SDT_TV_TC.getText().trim());
               Vector a = new Vector();
               Vector _dt = new Vector();
               a.add(tv.MaTV);
               a.add(tv.TenThanhVien);
               a.add(tv.SDT);
               a.add(tv.TienDaMua);
               a.add(tv.MaLoaiTV);
               _dt.add(a);
                  table_KQTraCuu.setModel(new DefaultTableModel(_dt,tblTitle));
                  }
                else
                    JOptionPane.showMessageDialog(this, "Số điện thoại thành viên không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
    }//GEN-LAST:event_btn_TraCuuActionPerformed

    private void btn_TraCuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TraCuuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_TraCuuMouseClicked

    private void btn_LamMoi_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_TCActionPerformed
        // TODO add your handling code here:
        txt_MaTV_TC.setText("");
        txt_SDT_TV_TC.setText("");
        table_KQTraCuu.setModel(new DefaultTableModel(new Vector(),tblTitle));
        
    }//GEN-LAST:event_btn_LamMoi_TCActionPerformed

    private void table_DS_LTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DS_LTVMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row =table_DS_LTV.rowAtPoint(p);
        String maltv = (String)model_LTV.getValueAt(row, 0).toString();
        String tenltv = (String)model_LTV.getValueAt(row, 1).toString();
        String tiencandat = (String)model_LTV.getValueAt(row, 2).toString();
        String phantramgiamgia = (String)model_LTV.getValueAt(row, 3).toString();
        txt_TenLTV.setText(tenltv);
        txt_MaLTV.setText(maltv);
        txt_TienCanDatLTV.setText(tiencandat);
        txt_PTGG_LTV.setText(phantramgiamgia);

    }//GEN-LAST:event_table_DS_LTVMouseClicked

    private void btn_LamMoi_LTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_LTVActionPerformed
        // TODO add your handling code here:
          txt_TenLTV.setText("");
        txt_MaLTV.setText("");
        txt_TienCanDatLTV.setText("");
        txt_PTGG_LTV.setText("");
        loadDS_LTV();
    }//GEN-LAST:event_btn_LamMoi_LTVActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
       
        txt_TenTV.setText("");
        txt_SDT_TV.setText("");
      
        cbb_LoaiTV.setSelectedIndex(0);
        txt_MaTV.setText("Automatic...");
        txt_TienDaMua.setText("");
        loadDS();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_ThemTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemTVActionPerformed
        // TODO add your handling code here:
        if(txt_TenTV.getText().equals("")||txt_SDT_TV.getText().trim().equals(""))
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
        else
        {
            if(daoTV.checkMembers_SDT(txt_SDT_TV.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Số điện thoại này đã đăng kí rồi!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                DTO_ThanhVien tv = new DTO_ThanhVien("X",txt_TenTV.getText(), txt_SDT_TV.getText().trim(), 0, "Bronze");
                if(daoTV.addTV(tv))
                    JOptionPane.showMessageDialog(this, "Đăng kí thành viên thành công!","Thông báo",JOptionPane.YES_OPTION);
                else
                    JOptionPane.showMessageDialog(this, "Đăng kí thành viên thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDS();
    }//GEN-LAST:event_btn_ThemTVActionPerformed

    private void btn_XoaTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTVActionPerformed
        // TODO add your handling code here:
        if(table_DSTV.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn thành viên nào!","Thông báo",JOptionPane.YES_OPTION);
        else
        {
            if(!daoTV.isTV_FKofAnotherTable(txt_MaTV.getText().trim()))
            {
                if(daoTV.delTV(txt_MaTV.getText().trim()))
                    JOptionPane.showMessageDialog(this, "Xóa thành viên thành công!","Thông báo",JOptionPane.YES_OPTION);
                else
                    JOptionPane.showMessageDialog(this, "Xóa thành viên thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
                JOptionPane.showMessageDialog(this, "Thành viên đang giữ khóa ngoại!","Thông báo",JOptionPane.YES_OPTION);
            
        }
        loadDS();
    }//GEN-LAST:event_btn_XoaTVActionPerformed

    private void btn_SuaTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaTVActionPerformed
        // TODO add your handling code here:
        if(table_DSTV.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn thành viên nào!","Thông báo",JOptionPane.YES_OPTION);
        else
        {
        if(txt_TenTV.getText().equals("")||txt_SDT_TV.getText().trim().equals(""))
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
        else
        {
            if(daoTV.checkMembers_SDT(txt_SDT_TV.getText().trim())&&!txt_SDT_TV.getText().trim().equals(daoTV.getSDT_from_MaTV(txt_TenTV.getText().trim())))
            {
                JOptionPane.showMessageDialog(this, "Số điện thoại này đã đăng kí rồi!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                DTO_ThanhVien tv = new DTO_ThanhVien(txt_MaTV.getText().trim(),txt_TenTV.getText(), txt_SDT_TV.getText().trim(), Integer.parseInt(txt_SDT_TV.getText().trim()), "Bronze");
                if(daoTV.updateTV(tv))
                    JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
                else
                    JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        }
        loadDS();
    }//GEN-LAST:event_btn_SuaTVActionPerformed

    private void txt_PTGG_LTVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PTGG_LTVKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() > '9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_PTGG_LTVKeyTyped

    private void txt_PTGG_LTVKeyTyped1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PTGG_LTVKeyTyped1
        // TODO add your handling code here:
        if(evt.getKeyChar() > '9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_PTGG_LTVKeyTyped1

    private void btn_ThemLTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLTVActionPerformed
        // TODO add your handling code here:
        if(checkFullInfo_LoaiTV())
        {
            if(!daoLTV.isExistLTV(txt_MaLTV.getText().trim()))
            {
                if(Integer.parseInt(txt_PTGG_LTV.getText().trim())>100 || Integer.parseInt(txt_PTGG_LTV.getText().trim())<0)
                {
                    JOptionPane.showMessageDialog(this, "Phần trăm giảm giá không hợp lệ!","Thông báo",JOptionPane.YES_OPTION);
                }
                else
                {
                    DTO_LoaiThanhVien ltv =new DTO_LoaiThanhVien(
                    txt_MaLTV.getText().trim(), txt_TenLTV.getText(), Integer.parseInt(txt_TienCanDatLTV.getText()),Integer.parseInt(txt_PTGG_LTV.getText())
                    );
                    if(daoLTV.addLTV(ltv))
                        JOptionPane.showMessageDialog(this, "Thêm mới loại thành viên thành công!","Thông báo",JOptionPane.YES_OPTION);
                    else
                        JOptionPane.showMessageDialog(this, "Thêm mới loại thành viên thất bại!","Thông báo",JOptionPane.YES_OPTION);
                }
            }
            else
                JOptionPane.showMessageDialog(this, "Mã loại thành viên đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
        loadDS_LTV();
    }//GEN-LAST:event_btn_ThemLTVActionPerformed

    private void btn_SuaLTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLTVActionPerformed
        // TODO add your handling code here:
        if(table_DS_LTV.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn thành viên nào!","Thông báo",JOptionPane.YES_OPTION);
        else
        {
            if(!checkFullInfo_LoaiTV())
                JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
            else
            {
                if(!daoLTV.isExistLTV(txt_MaLTV.getText().trim()))
                {
                    JOptionPane.showMessageDialog(this, "Mã loại thành viên không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
                }
                else
                {
                    if(Integer.parseInt(txt_PTGG_LTV.getText().trim())>100 || Integer.parseInt(txt_PTGG_LTV.getText().trim())<0)
                    {
                        JOptionPane.showMessageDialog(this, "Phần trăm giảm giá không hợp lệ!","Thông báo",JOptionPane.YES_OPTION);
                    }
                    else
                    {
                    DTO_LoaiThanhVien ltv =new DTO_LoaiThanhVien(
                    txt_MaLTV.getText().trim(), txt_TenLTV.getText(), Integer.parseInt(txt_TienCanDatLTV.getText()),Integer.parseInt(txt_PTGG_LTV.getText())
                    );
                    if(daoLTV.updateLTV(ltv))
                        JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
                    else
                        JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại!","Thông báo",JOptionPane.YES_OPTION);
                }}
            }
        }
        loadDS_LTV();
    }//GEN-LAST:event_btn_SuaLTVActionPerformed

    private void btn_XoaLTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLTVActionPerformed
        // TODO add your handling code here:
        if(table_DS_LTV.getSelectedRow()<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn thành viên nào!","Thông báo",JOptionPane.YES_OPTION);
        else
        {
            if(!daoLTV.isExistLTV(txt_MaLTV.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Mã loại thành viên không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                if(!daoLTV.isLTV_FKofAnotherTable(txt_MaLTV.getText().trim()))
                {
                    if(daoLTV.delLTV(txt_MaLTV.getText().trim()))
                        JOptionPane.showMessageDialog(this, "Xóa loại thành viên thành công!","Thông báo",JOptionPane.YES_OPTION);
                    else
                        JOptionPane.showMessageDialog(this, "Xóa loại thành viên thất bại!","Thông báo",JOptionPane.YES_OPTION);
                }
                else
                    JOptionPane.showMessageDialog(this, "Loại thành viên đang giữ khóa ngoại!","Thông báo",JOptionPane.YES_OPTION);
            
        }}
        loadDS_LTV();
    }//GEN-LAST:event_btn_XoaLTVActionPerformed

    private void txt_SDT_TVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDT_TVKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_SDT_TVKeyTyped

    private void txt_SDT_TV_TCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDT_TV_TCKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_SDT_TV_TCKeyTyped


    public void loadCB_LoaiTV()
    {
        ArrayList<DTO_LoaiThanhVien> cbb = DAO_LoaiThanhVien.listLTV();
         cbb_LoaiTV.removeAllItems();
        for(DTO_LoaiThanhVien i : cbb)
        {
            cbb_LoaiTV.addItem(i.TenLoaiTV);
        }
    }
    
    public boolean checkFullInfo_LoaiTV()
    {
        JTextField[] ds = new JTextField[]{txt_MaLTV,txt_TenLTV,txt_TienCanDatLTV,txt_PTGG_LTV};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    
    public void phanquyen()
    {
        txt_MaLTV.setEnabled(false);txt_TenLTV.setEnabled(false);txt_PTGG_LTV.setEnabled(false);txt_TienCanDatLTV.setEnabled(false);
        btn_LamMoi_LTV.setEnabled(false);btn_SuaLTV.setEnabled(false);btn_ThemLTV.setEnabled(false);btn_XoaLTV.setEnabled(false);
        table_DS_LTV.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_LamMoi_LTV;
    private javax.swing.JButton btn_LamMoi_TC;
    private javax.swing.JButton btn_SuaLTV;
    private javax.swing.JButton btn_SuaTV;
    private javax.swing.JButton btn_ThemLTV;
    private javax.swing.JButton btn_ThemTV;
    private javax.swing.JButton btn_TraCuu;
    private javax.swing.JButton btn_XoaLTV;
    private javax.swing.JButton btn_XoaTV;
    private javax.swing.JComboBox<String> cbb_LoaiTV;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_DSTV;
    private javax.swing.JTable table_DS_LTV;
    private javax.swing.JTable table_KQTraCuu;
    private javax.swing.JTextField txt_MaLTV;
    private javax.swing.JTextField txt_MaTV;
    private javax.swing.JTextField txt_MaTV_TC;
    private javax.swing.JTextField txt_PTGG_LTV;
    private javax.swing.JTextField txt_SDT_TV;
    private javax.swing.JTextField txt_SDT_TV_TC;
    private javax.swing.JTextField txt_TenLTV;
    private javax.swing.JTextField txt_TenTV;
    private javax.swing.JTextField txt_TienCanDatLTV;
    private javax.swing.JTextField txt_TienDaMua;
    // End of variables declaration//GEN-END:variables

}
