package GUI;

import DAO.DAO_KeDat;
import DAO.DAO_NXB;
import DAO.DAO_Tang;
import DAO.DAO_TheLoai;
import DTO.DTO_KeDat;
import DTO.DTO_NXB;
import DTO.DTO_PhieuGG;
import DTO.DTO_Tang;
import DTO.DTO_TheLoai;
import java.awt.Point;
import java.util.List;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_QLHeThongVatTu extends javax.swing.JPanel {
    DAO_KeDat _kedat = new DAO_KeDat();
    DAO_Tang _tang = new DAO_Tang();
    DAO_NXB _nxb = new DAO_NXB();
    DAO_TheLoai _theloai = new DAO_TheLoai();
    
    DefaultTableModel modelTang = new DefaultTableModel();
    Vector tang = new Vector();
    public Vector tblTang = new Vector();
    DefaultTableModel modelKe = new DefaultTableModel();
    Vector ke = new Vector();
    public Vector tblKe= new Vector();
    DefaultTableModel modelNXB = new DefaultTableModel();
    Vector nxb = new Vector();
    public Vector tblnxb = new Vector();
    DefaultTableModel modelTheLoai = new DefaultTableModel();
    Vector theloai = new Vector();
    public Vector tbltheloai = new Vector();
    /**
     * Creates new form panel_QLHeThongVatTu
     */
    public panel_QLHeThongVatTu() {
        initComponents();
        loadTitleKe();
        loadDSKe();
        loadTitleTang();
        loadDSTang();
        loadTitleTheLoai();
        loadDSTheLoai();
        loadTitleNXB();
        loadDSNXB();
    }
    public void loadTitleKe()
    {
 
        tblKe.add("Mã kệ");
        tblKe.add("Tên kệ");
        modelKe.setColumnIdentifiers(tblKe);
    }
    

    public void loadDSKe()
    {
        modelKe=new DefaultTableModel();
        modelKe.setColumnIdentifiers(tblKe);
       List<DTO_KeDat> lst = _kedat.getDS_KeDat();
        for(DTO_KeDat i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaKe);
            a.add(i.TenKe);
            ke.add(a);
            modelKe.addRow(a);
        }
        table_DSKeDat.setModel(modelKe);
    }
    public void loadTitleTang()
    {
        tblTang.add("Mã tầng");
        tblTang.add("Tên tầng");
        modelTang.setColumnIdentifiers(tblTang);
    }
    public void loadDSTang()
    {
        modelTang = new DefaultTableModel();
        modelTang.setColumnIdentifiers(tblTang);
        tang = new Vector();
       List<DTO_Tang> lst = _tang.getDS_Tang();
        for(DTO_Tang i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaTang);
            a.add(i.TenTang);
            tang.add(a);
            modelTang.addRow(a);
        }
        table_DSTang.setModel(modelTang);
    }
    public void loadTitleTheLoai()
    {
        tbltheloai.add("Mã thể loại");
        tbltheloai.add("Tên thể loại");
        modelTheLoai.setColumnIdentifiers(tbltheloai);
    }
    public void loadDSTheLoai()
    {
        modelTheLoai=new DefaultTableModel();
        modelTheLoai.setColumnIdentifiers(tbltheloai);
        theloai=new Vector();
       List<DTO_TheLoai> lst = _theloai.getDS_TheLoai();
        for(DTO_TheLoai i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaTheLoai);
            a.add(i.TenTheLoai);
            theloai.add(a);
            modelTheLoai.addRow(a);
        }
        table_DS_TL.setModel(modelTheLoai);
    }
    public void loadTitleNXB()
    {
        tblnxb.add("Mã NXB");
        tblnxb.add("Tên NXB");
        modelNXB.setColumnIdentifiers(tblnxb);
    }
    public void loadDSNXB()
    {
        modelNXB=new DefaultTableModel();
        modelNXB.setColumnIdentifiers(tblnxb);
        nxb=new Vector();
       List<DTO_NXB> lst = _nxb.getDS_NXB();
        for(DTO_NXB i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaNXB);
            a.add(i.TenNXB);
            nxb.add(a);
            modelNXB.addRow(a);
        }
        table_DS_NXB.setModel(modelNXB);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_TenTang = new javax.swing.JTextField();
        txt_MaTang = new javax.swing.JTextField();
        btn_Luu_Tang = new javax.swing.JButton();
        btn_ThemTang = new javax.swing.JButton();
        btn_LamMoi_Tang = new javax.swing.JButton();
        btn_XoaTang = new javax.swing.JButton();
        btn_SuaTang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_DSTang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_TenKe = new javax.swing.JTextField();
        txt_MaKe = new javax.swing.JTextField();
        btn_Luu_KeDat = new javax.swing.JButton();
        btn_ThemLTV1 = new javax.swing.JButton();
        btn_LamMoi_LTV1 = new javax.swing.JButton();
        btn_XoaLTV1 = new javax.swing.JButton();
        btn_SuaLTV1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_DSKeDat = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_TenNXB = new javax.swing.JTextField();
        txt_MaNXB = new javax.swing.JTextField();
        btn_Luu_NXB = new javax.swing.JButton();
        btn_ThemNXB = new javax.swing.JButton();
        btn_LamMoi_NXB = new javax.swing.JButton();
        btn_XoaNXB = new javax.swing.JButton();
        btn_SuaNXB = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_DS_NXB = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_TenTL = new javax.swing.JTextField();
        txt_MaTL = new javax.swing.JTextField();
        btn_Luu_TheLoai = new javax.swing.JButton();
        btn_ThemTL = new javax.swing.JButton();
        btn_LamMoi_TL = new javax.swing.JButton();
        btn_XoaTL = new javax.swing.JButton();
        btn_SuaTL = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_DS_TL = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Thông tin các tầng:");
        jLabel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Mã tầng:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Tên tầng:");

        txt_TenTang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_MaTang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_Luu_Tang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Luu_Tang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_Luu_Tang.setText("Lưu");
        btn_Luu_Tang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Luu_Tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Luu_TangActionPerformed(evt);
            }
        });

        btn_ThemTang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemTang.setText("Thêm tầng");
        btn_ThemTang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemTang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemTangActionPerformed(evt);
            }
        });

        btn_LamMoi_Tang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi_Tang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_Tang.setText(" Làm mới");
        btn_LamMoi_Tang.setActionCommand("Làm mới");
        btn_LamMoi_Tang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi_Tang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_TangActionPerformed(evt);
            }
        });

        btn_XoaTang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaTang.setText("Xóa tầng");
        btn_XoaTang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTangActionPerformed(evt);
            }
        });

        btn_SuaTang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaTang.setText("Sửa tầng");
        btn_SuaTang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaTangActionPerformed(evt);
            }
        });

        table_DSTang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DSTang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DSTang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_DSTang.setRowHeight(35);
        table_DSTang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSTangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_DSTang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenTang, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaTang, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SuaTang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_XoaTang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamMoi_Tang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Luu_Tang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThemTang))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_ThemTang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SuaTang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaTang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_LamMoi_Tang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Luu_Tang))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_MaTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_TenTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Thông tin các kệ đặt:");
        jLabel5.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Mã kệ:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Tên kệ:");

        txt_TenKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_MaKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_Luu_KeDat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Luu_KeDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_Luu_KeDat.setText("Lưu");
        btn_Luu_KeDat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Luu_KeDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Luu_KeDatActionPerformed(evt);
            }
        });

        btn_ThemLTV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemLTV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemLTV1.setText("Thêm kệ đặt");
        btn_ThemLTV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemLTV1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemLTV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLTV1ActionPerformed(evt);
            }
        });

        btn_LamMoi_LTV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi_LTV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_LTV1.setText(" Làm mới");
        btn_LamMoi_LTV1.setActionCommand("Làm mới");
        btn_LamMoi_LTV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi_LTV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_LTV1ActionPerformed(evt);
            }
        });

        btn_XoaLTV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaLTV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaLTV1.setText("Xóa kệ đặt");
        btn_XoaLTV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaLTV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLTV1ActionPerformed(evt);
            }
        });

        btn_SuaLTV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaLTV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaLTV1.setText("Sửa kệ đặt");
        btn_SuaLTV1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaLTV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLTV1ActionPerformed(evt);
            }
        });

        table_DSKeDat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DSKeDat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DSKeDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_DSKeDat.setRowHeight(35);
        table_DSKeDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSKeDatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_DSKeDat);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenKe, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaKe, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SuaLTV1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_XoaLTV1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamMoi_LTV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Luu_KeDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThemLTV1))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_ThemLTV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SuaLTV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaLTV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_LamMoi_LTV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Luu_KeDat))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_MaKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_TenKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Thông tin các NXB:");
        jLabel6.setToolTipText("");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Mã NXB:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Tên NXB:");

        txt_TenNXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_MaNXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_Luu_NXB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Luu_NXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_Luu_NXB.setText("Lưu");
        btn_Luu_NXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Luu_NXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Luu_NXBActionPerformed(evt);
            }
        });

        btn_ThemNXB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemNXB.setText("Thêm NXB");
        btn_ThemNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemNXB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemNXBActionPerformed(evt);
            }
        });

        btn_LamMoi_NXB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi_NXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_NXB.setText(" Làm mới");
        btn_LamMoi_NXB.setActionCommand("Làm mới");
        btn_LamMoi_NXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi_NXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_NXBActionPerformed(evt);
            }
        });

        btn_XoaNXB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaNXB.setText("Xóa NXB");
        btn_XoaNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaNXBActionPerformed(evt);
            }
        });

        btn_SuaNXB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaNXB.setText("Sửa NXB");
        btn_SuaNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaNXBActionPerformed(evt);
            }
        });

        table_DS_NXB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DS_NXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DS_NXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_DS_NXB.setRowHeight(35);
        table_DS_NXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DS_NXBMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_DS_NXB);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SuaNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_XoaNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamMoi_NXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Luu_NXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThemNXB))
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_ThemNXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SuaNXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaNXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_LamMoi_NXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Luu_NXB))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txt_MaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txt_TenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Thông tin các thể loại:");
        jLabel7.setToolTipText("");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Mã thể loại:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Tên thể loại:");

        txt_TenTL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_MaTL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_Luu_TheLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Luu_TheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_Luu_TheLoai.setText("Lưu");
        btn_Luu_TheLoai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Luu_TheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Luu_TheLoaiActionPerformed(evt);
            }
        });

        btn_ThemTL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemTL.setText("Thêm TL");
        btn_ThemTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemTL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemTLActionPerformed(evt);
            }
        });

        btn_LamMoi_TL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi_TL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_TL.setText(" Làm mới");
        btn_LamMoi_TL.setActionCommand("Làm mới");
        btn_LamMoi_TL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi_TL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_TLActionPerformed(evt);
            }
        });

        btn_XoaTL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaTL.setText("Xóa TL");
        btn_XoaTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaTLActionPerformed(evt);
            }
        });

        btn_SuaTL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaTL.setText("Sửa TL");
        btn_SuaTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaTLActionPerformed(evt);
            }
        });

        table_DS_TL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DS_TL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DS_TL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_DS_TL.setRowHeight(35);
        table_DS_TL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DS_TLMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_DS_TL);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TenTL, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_SuaTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_XoaTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamMoi_TL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Luu_TheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThemTL))
                .addGap(24, 24, 24))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_ThemTL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SuaTL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaTL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_LamMoi_TL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Luu_TheLoai))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_MaTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txt_TenTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_DSTangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSTangMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = table_DSTang.rowAtPoint(p);
        String matang  = (String)modelTang.getValueAt(row, 0).toString();
        String tentang = (String)modelTang.getValueAt(row, 1).toString();
        txt_MaTang.setText(matang);
        txt_TenTang.setText(tentang);
    }//GEN-LAST:event_table_DSTangMouseClicked

    private void btn_LamMoi_TangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_TangActionPerformed
        // TODO add your handling code here:
        txt_MaTang.setText("");
        txt_TenTang.setText("");
    }//GEN-LAST:event_btn_LamMoi_TangActionPerformed

    private void table_DSKeDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSKeDatMouseClicked
        // TODO add your handling code here:
          Point p = evt.getPoint();
        int row = table_DSKeDat.rowAtPoint(p);
        String make  = (String)modelKe.getValueAt(row, 0).toString();
        String tenke = (String)modelKe.getValueAt(row, 1).toString();
        txt_MaKe.setText(make);
        txt_TenKe.setText(tenke);
    }//GEN-LAST:event_table_DSKeDatMouseClicked

    private void btn_LamMoi_LTV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_LTV1ActionPerformed
        // TODO add your handling code here:
        txt_MaKe.setText("");
        txt_TenKe.setText("");
    }//GEN-LAST:event_btn_LamMoi_LTV1ActionPerformed

    private void table_DS_TLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DS_TLMouseClicked
        // TODO add your handling code here:
           Point p = evt.getPoint();
        int row = table_DS_TL.rowAtPoint(p);
        String matl  = (String)modelTheLoai.getValueAt(row, 0).toString();
        String tentl = (String)modelTheLoai.getValueAt(row, 1).toString();
        txt_MaTL.setText(matl);
        txt_TenTL.setText(tentl);
    }//GEN-LAST:event_table_DS_TLMouseClicked

    private void btn_LamMoi_TLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_TLActionPerformed
        // TODO add your handling code here:
        txt_MaTL.setText("");
        txt_TenTL.setText("");
    }//GEN-LAST:event_btn_LamMoi_TLActionPerformed

    private void table_DS_NXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DS_NXBMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = table_DS_NXB.rowAtPoint(p);
        String manxb  = (String)modelNXB.getValueAt(row, 0).toString();
        String tennxb = (String)modelNXB.getValueAt(row, 1).toString();
        txt_MaNXB.setText(manxb);
        txt_TenNXB.setText(tennxb);
    }//GEN-LAST:event_table_DS_NXBMouseClicked

    private void btn_LamMoi_NXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_NXBActionPerformed
        // TODO add your handling code here:
        txt_MaNXB.setText("");
        txt_TenNXB.setText("");
    }//GEN-LAST:event_btn_LamMoi_NXBActionPerformed

    private boolean checkFullInformationTang()
    {
        JTextField[] ds = new JTextField[]{txt_MaTang,txt_TenTang};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    private boolean checkFullInformationKeDat()
    {
        JTextField[] ds = new JTextField[]{txt_MaKe,txt_TenKe};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    private boolean checkFullInformationNXB()
    {
        JTextField[] ds = new JTextField[]{txt_MaNXB,txt_TenNXB};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    private boolean checkFullInformationTheLoai()
    {
        JTextField[] ds = new JTextField[]{txt_MaTL,txt_TenTL};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
 
    private void btn_ThemTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemTangActionPerformed
        // TODO add your handling code here:
          if(checkFullInformationTang())
        {
            if(!_tang.checkExistPrimarykey(txt_MaTang.getText().trim()))
            {
                VisibleButton_Luu_Tang(true, btn_ThemTang);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã tầng đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_ThemTangActionPerformed

    private void btn_Luu_TangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Luu_TangActionPerformed
        // TODO add your handling code here:
        if(btn_ThemTang.isEnabled())
        {
            //Thêm
            DTO_Tang sp = new DTO_Tang(txt_MaTang.getText().trim(),txt_TenTang.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_tang.addSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Thêm tầng mới thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, thêm thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            
        }
        else if(btn_XoaTang.isEnabled())
        {
            if(_tang.delSanPham(txt_MaTang.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Xóa tầng thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Tầng đang giữ khóa ngoại, xóa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            //Xóa
        }
        else if(btn_SuaTang.isEnabled())
        {
          DTO_Tang sp = new DTO_Tang(txt_MaTang.getText().trim(),txt_TenTang.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_tang.updateSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, sửa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDSTang();
        VisibleButton_Luu_Tang(false, btn_LamMoi_Tang);
    }//GEN-LAST:event_btn_Luu_TangActionPerformed

    private void btn_SuaTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaTangActionPerformed
        // TODO add your handling code here:
           if(checkFullInformationTang())
        {
            if(_tang.checkExistPrimarykey(txt_MaTang.getText().trim()))
            {
        
                VisibleButton_Luu_Tang(true, btn_SuaTang);
               
            }
            else
                JOptionPane.showMessageDialog(this, "Mã tầng đang sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_SuaTangActionPerformed

    private void btn_XoaTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTangActionPerformed
        // TODO add your handling code here:
         if(!_tang.checkExistForeignkey(txt_MaTang.getText().trim()))
         {
             VisibleButton_Luu_Tang(true, btn_XoaTang); 
         }
        else
        {
            JOptionPane.showMessageDialog(this, "Tầng đang giữ khóa ngoại, không thể xóa!","Thông báo",JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btn_XoaTangActionPerformed


    private void btn_ThemLTV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLTV1ActionPerformed
        // TODO add your handling code here:
        if(checkFullInformationKeDat())
        {
            if(!_kedat.checkExistPrimarykey(txt_MaKe.getText().trim()))
            {
         VisibleButton_Luu_KeDat(true, btn_ThemLTV1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã kệ đặt đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_ThemLTV1ActionPerformed

    private void btn_XoaLTV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLTV1ActionPerformed
        // TODO add your handling code here:
             if(!_kedat.checkExistForeignkey(txt_MaKe.getText().trim()))
         {
                 VisibleButton_Luu_KeDat(true, btn_XoaLTV1);
         }
        else
        {
            JOptionPane.showMessageDialog(this, "Kệ đặt đang giữ khóa ngoại, không thể xóa!","Thông báo",JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btn_XoaLTV1ActionPerformed


    
    
    
    
    private void btn_SuaLTV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLTV1ActionPerformed
        // TODO add your handling code here:
         if(checkFullInformationKeDat())
        {
            if(_kedat.checkExistPrimarykey(txt_MaKe.getText().trim()))
            {
        
                VisibleButton_Luu_KeDat(true, btn_SuaLTV1);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã kệ đang sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_SuaLTV1ActionPerformed

    private void btn_Luu_KeDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Luu_KeDatActionPerformed
        // TODO add your handling code here:
        if(btn_ThemLTV1.isEnabled())
        {
            //Thêm
            DTO_KeDat sp = new DTO_KeDat(txt_MaKe.getText().trim(),txt_TenKe.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_kedat.addSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Thêm kệ đặt mới thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, thêm thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            
        }
        else if(btn_XoaLTV1.isEnabled())
        {
            if(_kedat.delSanPham(txt_MaKe.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Xóa kệ đặt thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Kệ đang giữ khóa ngoại, xóa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            //Xóa
        }
        else if(btn_SuaLTV1.isEnabled())
        {
          DTO_KeDat sp = new DTO_KeDat(txt_MaKe.getText().trim(),txt_TenKe.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_kedat.updateSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, sửa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDSKe();
            VisibleButton_Luu_KeDat(false, btn_LamMoi_LTV1);
    }//GEN-LAST:event_btn_Luu_KeDatActionPerformed

    private void btn_ThemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemNXBActionPerformed
        // TODO add your handling code here:
        if(checkFullInformationNXB())
        {
            if(!_nxb.checkExistPrimarykey(txt_MaNXB.getText().trim()))
            {
         VisibleButton_Luu_NXB(true, btn_ThemNXB);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã nhà xuất bản đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_ThemNXBActionPerformed

    private void btn_SuaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaNXBActionPerformed
        // TODO add your handling code here:
        if(checkFullInformationNXB())
        {
            if(_nxb.checkExistPrimarykey(txt_MaNXB.getText().trim()))
            {
        
                VisibleButton_Luu_NXB(true, btn_SuaNXB);
               
            }
            else
                JOptionPane.showMessageDialog(this, "Mã nhà xuất bản đang sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_SuaNXBActionPerformed

    private void btn_XoaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaNXBActionPerformed
        // TODO add your handling code here:
         if(!_nxb.checkExistForeignkey(txt_MaNXB.getText().trim()))
         {
             VisibleButton_Luu_NXB(true, btn_XoaNXB); 
         }
        else
        {
            JOptionPane.showMessageDialog(this, "Tầng đang giữ khóa ngoại, không thể xóa!","Thông báo",JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btn_XoaNXBActionPerformed

    private void btn_Luu_NXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Luu_NXBActionPerformed
        // TODO add your handling code here:
         if(btn_ThemNXB.isEnabled())
        {
            //Thêm
            DTO_NXB sp = new DTO_NXB(txt_MaNXB.getText().trim(),txt_TenNXB.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_nxb.addSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Thêm nhà xuất bản thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, thêm thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            
        }
        else if(btn_XoaNXB.isEnabled())
        {
            if(_nxb.delSanPham(txt_MaNXB.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Xóa nhà xuất bản thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Tầng đang giữ khóa ngoại, xóa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            //Xóa
        }
        else if(btn_SuaNXB.isEnabled())
        {
        DTO_NXB sp = new DTO_NXB(txt_MaNXB.getText().trim(),txt_TenNXB.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_nxb.updateSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, sửa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDSNXB();
        VisibleButton_Luu_NXB(false, btn_LamMoi_NXB);
    }//GEN-LAST:event_btn_Luu_NXBActionPerformed

    private void btn_ThemTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemTLActionPerformed
        // TODO add your handling code here:
         if(checkFullInformationTheLoai())
        {
            if(!_theloai.checkExistPrimarykey(txt_MaTL.getText().trim()))
            {
         VisibleButton_Luu_TheLoai(true, btn_ThemTL);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã thể loại đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_ThemTLActionPerformed

    private void btn_SuaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaTLActionPerformed
        // TODO add your handling code here:
        if(checkFullInformationTheLoai())
        {
            if(_theloai.checkExistPrimarykey(txt_MaTL.getText().trim()))
            {
        
                VisibleButton_Luu_TheLoai(true, btn_SuaTL);
               
            }
            else
                JOptionPane.showMessageDialog(this, "Mã thể loại đang sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_SuaTLActionPerformed

    private void btn_XoaTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaTLActionPerformed
        // TODO add your handling code here:
          if(!_theloai.checkExistForeignkey(txt_MaTL.getText().trim()))
         {
             VisibleButton_Luu_TheLoai(true, btn_XoaTL); 
         }
        else
        {
            JOptionPane.showMessageDialog(this, "Thể loại đang giữ khóa ngoại, không thể xóa!","Thông báo",JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btn_XoaTLActionPerformed

    private void btn_Luu_TheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Luu_TheLoaiActionPerformed
        // TODO add your handling code here:
          if(btn_ThemTL.isEnabled())
        {
            //Thêm
            DTO_TheLoai sp = new DTO_TheLoai(txt_MaTL.getText().trim(),txt_TenTL.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_theloai.addSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Thêm thể loại thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, thêm thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            
        }
        else if(btn_XoaTL.isEnabled())
        {
            if(_theloai.delSanPham(txt_MaTL.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Xóa thể loại thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thể loại đang giữ khóa ngoại, xóa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            //Xóa
        }
        else if(btn_SuaTL.isEnabled())
        {
      DTO_TheLoai sp = new DTO_TheLoai(txt_MaTL.getText().trim(),txt_TenTL.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_theloai.updateSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, sửa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDSTheLoai();
        VisibleButton_Luu_TheLoai(false, btn_LamMoi_TL);
    }//GEN-LAST:event_btn_Luu_TheLoaiActionPerformed

    
    private void VisibleButton_Luu_Tang(boolean bool, JButton btn)
    {
        if(bool)
        {
            JButton[] ds = new JButton[]{btn_Luu_Tang};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
            ds = new JButton[]{btn_ThemTang,btn_SuaTang,btn_XoaTang};
            for(JButton i : ds)
            {
                if(i!=btn)
                    i.setEnabled(false);
            }
        }
        else
        {
            JButton[] ds = new JButton[]{btn_Luu_Tang};
            for(JButton i : ds)
            {
                i.setEnabled(false);
            }
            ds = new JButton[]{btn_ThemTang,btn_SuaTang,btn_XoaTang};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
        }
    }
    
    
    
        private void VisibleButton_Luu_KeDat(boolean bool, JButton btn)
    {
        if(bool)
        {
            JButton[] ds = new JButton[]{btn_Luu_KeDat};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
            ds = new JButton[]{btn_ThemLTV1,btn_SuaLTV1,btn_XoaLTV1};
            for(JButton i : ds)
            {
                if(i!=btn)
                    i.setEnabled(false);
            }
        }
        else
        {
            JButton[] ds = new JButton[]{btn_Luu_KeDat};
            for(JButton i : ds)
            {
                i.setEnabled(false);
            }
            ds = new JButton[]{btn_ThemLTV1,btn_SuaLTV1,btn_XoaLTV1};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
        }
    }
         private void VisibleButton_Luu_NXB(boolean bool, JButton btn)
    {
        if(bool)
        {
            JButton[] ds = new JButton[]{btn_Luu_NXB};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
            ds = new JButton[]{btn_ThemNXB,btn_SuaNXB,btn_XoaNXB};
            for(JButton i : ds)
            {
                if(i!=btn)
                    i.setEnabled(false);
            }
        }
        else
        {
            JButton[] ds = new JButton[]{btn_Luu_NXB};
            for(JButton i : ds)
            {
                i.setEnabled(false);
            }
            ds = new JButton[]{btn_ThemNXB,btn_SuaNXB,btn_XoaNXB};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
        }
    }
private void VisibleButton_Luu_TheLoai(boolean bool, JButton btn)
    {
        if(bool)
        {
            JButton[] ds = new JButton[]{btn_Luu_TheLoai};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
            ds = new JButton[]{btn_ThemTL,btn_SuaTL,btn_XoaTL};
            for(JButton i : ds)
            {
                if(i!=btn)
                    i.setEnabled(false);
            }
        }
        else
        {
            JButton[] ds = new JButton[]{btn_Luu_TheLoai};
            for(JButton i : ds)
            {
                i.setEnabled(false);
            }
            ds = new JButton[]{btn_ThemTL,btn_SuaTL,btn_XoaTL};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi_LTV1;
    private javax.swing.JButton btn_LamMoi_NXB;
    private javax.swing.JButton btn_LamMoi_TL;
    private javax.swing.JButton btn_LamMoi_Tang;
    private javax.swing.JButton btn_Luu_KeDat;
    private javax.swing.JButton btn_Luu_NXB;
    private javax.swing.JButton btn_Luu_Tang;
    private javax.swing.JButton btn_Luu_TheLoai;
    private javax.swing.JButton btn_SuaLTV1;
    private javax.swing.JButton btn_SuaNXB;
    private javax.swing.JButton btn_SuaTL;
    private javax.swing.JButton btn_SuaTang;
    private javax.swing.JButton btn_ThemLTV1;
    private javax.swing.JButton btn_ThemNXB;
    private javax.swing.JButton btn_ThemTL;
    private javax.swing.JButton btn_ThemTang;
    private javax.swing.JButton btn_XoaLTV1;
    private javax.swing.JButton btn_XoaNXB;
    private javax.swing.JButton btn_XoaTL;
    private javax.swing.JButton btn_XoaTang;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable table_DSKeDat;
    private javax.swing.JTable table_DSTang;
    private javax.swing.JTable table_DS_NXB;
    private javax.swing.JTable table_DS_TL;
    private javax.swing.JTextField txt_MaKe;
    private javax.swing.JTextField txt_MaNXB;
    private javax.swing.JTextField txt_MaTL;
    private javax.swing.JTextField txt_MaTang;
    private javax.swing.JTextField txt_TenKe;
    private javax.swing.JTextField txt_TenNXB;
    private javax.swing.JTextField txt_TenTL;
    private javax.swing.JTextField txt_TenTang;
    // End of variables declaration//GEN-END:variables
}
