package GUI;

import DAO.DAO_TaiKhoan;
import DTO.DTO_TaiKhoan;
import java.awt.Point;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_QLTaiKhoan extends javax.swing.JPanel {
    DefaultTableModel modelDS = new DefaultTableModel();
    Vector data = new Vector();
    public Vector tblTitle = new Vector();
    DAO_TaiKhoan _dao=new DAO_TaiKhoan();
    /**
     * Creates new form panel_QLTaiKhoan
     */
    public String tenDN="";
    public String id ="",quyen=""; public boolean flag=true;
    public panel_QLTaiKhoan(String tendn) {
        
        initComponents();
        pen_DMK.setVisible(false);       
       
        this.tenDN=tendn;
        
        loadTTTK();
        
        if(DAO_TaiKhoan.getMaQuyenfromMaTK(tendn).trim().equals("user"))
            phanquyen();
        else
        {loadTitle();
        loadDS();}
    }

    public void loadTitle()
    {
 
        tblTitle.add("Mã tài khoản");
        tblTitle.add("Tên đăng nhập"); 
        tblTitle.add("Mật khẩu");
        tblTitle.add("Họ tên");
        tblTitle.add("SDT"); 
        tblTitle.add("Mã quyền"); 
        tblTitle.add("Bị khóa"); 
        modelDS.setColumnIdentifiers(tblTitle);
        table_DSTK.setModel(modelDS); 
    }
    public void loadTTTK()
    {
     String tenquyen;
             DTO_TaiKhoan tv = _dao.getTaiKhoan_from_MaTKDN(tenDN);
     
               lbl_SDT.setText(tv.SDT);
               lbl_TenDN.setText(tv.TenDangNhap);
                 if(tv.MaQuyen.equals("user"))
               {
                   tenquyen="Quyền User";
               }
              else
               {
                   tenquyen="Quyền Admin";
               }
                   lbl_Quyen.setText(tenquyen);
                   lbl_HoTen.setText(tv.HoTen);
                   lbl_MaTK.setText(tv.MaTaiKhoan);
                   field_pasword.setText(tv.MatKhau);
                   
    }
    public void loadDS()
    {
        modelDS =new DefaultTableModel();
        modelDS.setColumnIdentifiers(tblTitle);
       List<DTO_TaiKhoan> lst = _dao.getDS_TaiKhoan();
        for(DTO_TaiKhoan i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaTaiKhoan);
            a.add(i.TenDangNhap);
            a.add(i.MatKhau);
            a.add(i.HoTen);
            a.add(i.SDT);
            a.add(i.MaQuyen);
            a.add(i.BiKhoa);
            modelDS.addRow(a);
        }
        table_DSTK.setModel(modelDS);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_MaTK = new javax.swing.JTextField();
        txt_TenDN = new javax.swing.JTextField();
        txt_HoTen = new javax.swing.JTextField();
        btn_ThemTK = new javax.swing.JButton();
        btn_SuaTK = new javax.swing.JButton();
        btn_KhoaMoTK = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_BoChon = new javax.swing.JButton();
        txt_MK = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cbb_Quyen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DSTK = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl_HoTen = new javax.swing.JLabel();
        lbl_MaTK = new javax.swing.JLabel();
        lbl_Quyen = new javax.swing.JLabel();
        lbl_SDT = new javax.swing.JLabel();
        lbl_TenDN = new javax.swing.JLabel();
        btn_DoiMK = new javax.swing.JButton();
        field_pasword = new javax.swing.JPasswordField();
        pen_DMK = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_CapNhatMK = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        txt_MatKhauCu = new javax.swing.JPasswordField();
        jLabel51 = new javax.swing.JLabel();
        txt_MatKhaiMoi = new javax.swing.JPasswordField();
        jLabel52 = new javax.swing.JLabel();
        txt_XacNhanMK = new javax.swing.JPasswordField();
        btn_LamMoi_DMK = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Quản lý tài khoản (Chỉ Admin):");
        jLabel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Mã tài khoản:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Tên đăng nhập:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Mật khẩu:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Quyền:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Họ tên:");

        txt_MaTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_MaTK.setText("Automatic...");

        txt_TenDN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_HoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_ThemTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-group.png"))); // NOI18N
        btn_ThemTK.setText("Thêm tài khoản");
        btn_ThemTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemTKActionPerformed(evt);
            }
        });

        btn_SuaTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaTK.setText("Sửa thông tin");
        btn_SuaTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaTKActionPerformed(evt);
            }
        });

        btn_KhoaMoTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_KhoaMoTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blocked.png"))); // NOI18N
        btn_KhoaMoTK.setText("Khóa/Mở tài khoản");
        btn_KhoaMoTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_KhoaMoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KhoaMoTKActionPerformed(evt);
            }
        });

        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi.setText(" Làm mới");
        btn_LamMoi.setActionCommand("Làm mới");
        btn_LamMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_BoChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_BoChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negative.png"))); // NOI18N
        btn_BoChon.setText("Bỏ chọn");
        btn_BoChon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_BoChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BoChonActionPerformed(evt);
            }
        });

        txt_MK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_SDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SDTKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Số điện thoại:");

        cbb_Quyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_Quyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Admin" }));
        cbb_Quyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_QuyenActionPerformed(evt);
            }
        });

        table_DSTK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DSTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DSTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_DSTK.setRowHeight(35);
        table_DSTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_DSTK);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Quản lý tài khoản (Chỉ Admin):");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MK)
                                    .addComponent(txt_TenDN)
                                    .addComponent(txt_HoTen)
                                    .addComponent(txt_SDT)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbb_Quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btn_ThemTK)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_SuaTK)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_KhoaMoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_BoChon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_MK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbb_Quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemTK)
                    .addComponent(btn_SuaTK)
                    .addComponent(btn_KhoaMoTK)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_BoChon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Thông tin tài khoản:");
        jLabel6.setToolTipText("");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setText("Mã tài khoản:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Họ tên:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("Số điện thoại:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setText("Quyền:");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setText("Mật khẩu:");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setText("Tên đăng nhập:");

        lbl_HoTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_HoTen.setText("Loading...");

        lbl_MaTK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_MaTK.setText("Loading...");

        lbl_Quyen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Quyen.setText("Loading...");

        lbl_SDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SDT.setText("Loading...");

        lbl_TenDN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TenDN.setText("Loading...");

        btn_DoiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N
        btn_DoiMK.setText("Đổi mật khẩu");
        btn_DoiMK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_DoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DoiMKActionPerformed(evt);
            }
        });

        field_pasword.setEditable(false);
        field_pasword.setText("jPasswordField1");
        field_pasword.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SDT)
                            .addComponent(lbl_MaTK)
                            .addComponent(lbl_HoTen)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TenDN)
                                    .addComponent(lbl_Quyen)
                                    .addComponent(field_pasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_DoiMK)))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lbl_HoTen))
                            .addComponent(lbl_MaTK))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lbl_Quyen))
                            .addComponent(lbl_SDT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(lbl_TenDN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(field_pasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_DoiMK)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(4, 4, 4)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pen_DMK.setBackground(new java.awt.Color(255, 255, 255));
        pen_DMK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setText("Đổi mật khẩu:");
        jLabel9.setToolTipText("");

        btn_CapNhatMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_CapNhatMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updatePas.png"))); // NOI18N
        btn_CapNhatMK.setText("Cập nhật");
        btn_CapNhatMK.setToolTipText("");
        btn_CapNhatMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatMKActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel50.setText("Mật khẩu cũ:");

        txt_MatKhauCu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel51.setText("Mật khẩu mới:");

        txt_MatKhaiMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel52.setText("Xác nhận mật khẩu:");

        txt_XacNhanMK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_LamMoi_DMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi_DMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_DMK.setText(" Làm mới");
        btn_LamMoi_DMK.setActionCommand("Làm mới");
        btn_LamMoi_DMK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout pen_DMKLayout = new javax.swing.GroupLayout(pen_DMK);
        pen_DMK.setLayout(pen_DMKLayout);
        pen_DMKLayout.setHorizontalGroup(
            pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pen_DMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pen_DMKLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pen_DMKLayout.createSequentialGroup()
                        .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pen_DMKLayout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pen_DMKLayout.createSequentialGroup()
                                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pen_DMKLayout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pen_DMKLayout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addGap(91, 91, 91)))
                                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MatKhaiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_XacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_LamMoi_DMK, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pen_DMKLayout.createSequentialGroup()
                        .addComponent(btn_CapNhatMK, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        pen_DMKLayout.setVerticalGroup(
            pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pen_DMKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txt_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(txt_MatKhaiMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txt_XacNhanMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pen_DMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CapNhatMK)
                    .addComponent(btn_LamMoi_DMK))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pen_DMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pen_DMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btn_DoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DoiMKActionPerformed
        // TODO add your handling code here:
        pen_DMK.setVisible(true);
    }//GEN-LAST:event_btn_DoiMKActionPerformed

    private void btn_CapNhatMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatMKActionPerformed
        // TODO add your handling code here:
    
        boolean bikhoa=false;            
        if(field_pasword.getText().equals(txt_MatKhauCu.getText()))
        {
            String flag = (lbl_Quyen.getText().toString().equals("Quyền User"))?"user":"admin";
            DTO_TaiKhoan tk =new DTO_TaiKhoan(
                    lbl_MaTK.getText().trim(), lbl_TenDN.getText(),txt_MatKhaiMoi.getText(),lbl_HoTen.getText(),lbl_SDT.getText(),flag,bikhoa);
            if(txt_MatKhaiMoi.getText().equals(txt_XacNhanMK.getText()))
            {
                if(_dao.updateTaiKhoan(tk))
                
                    JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!","Thông báo",JOptionPane.YES_OPTION);

                else
                    JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Mã xác nhận không trùng mật khẩu mới!","Thông báo",JOptionPane.YES_OPTION);
            }
        }  
        else
        {
            JOptionPane.showMessageDialog(this, "Mật khẩu cũ không đúng!","Thông báo",JOptionPane.YES_OPTION);
        }

    }//GEN-LAST:event_btn_CapNhatMKActionPerformed

//    private void DangNhapLai()
//    {
//         {
//            int choice = JOptionPane.showConfirmDialog(null, "Đổi mật khẩu thành công!Bạn có muốn đăng nhập lại không?", "Thông báo", JOptionPane.YES_NO_OPTION);
//            if (choice == JOptionPane.YES_OPTION) {
//             Nếu người dùng chọn "Có", gọi form đăng nhập
//            frm_DangNhap loginForm = new frm_DangNhap();
//            loginForm.setVisible(true);
//        } else {
//             Nếu người dùng chọn "Không", kết thúc ứng dụng
//            System.exit(0);
//        }
//         } 
//    }
    private void table_DSTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSTKMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row =table_DSTK.rowAtPoint(p);
        String matk = (String)modelDS.getValueAt(row, 0).toString();
        String tendn = (String)modelDS.getValueAt(row, 1).toString();
        String mk = (String)modelDS.getValueAt(row, 2).toString();
        String hoten = (String)modelDS.getValueAt(row, 3).toString();
        String sdt=(String)modelDS.getValueAt(row, 4).toString();
         String maquyen=(String)modelDS.getValueAt(row, 5).toString();
          String bikhoa=(String)modelDS.getValueAt(row, 6).toString();
        
          id=matk;
          flag = (bikhoa.equals("false"))?false:true;
          quyen = maquyen;
        txt_MaTK.setText(matk);
        txt_TenDN.setText(tendn);
        txt_MK.setText(mk);
        txt_HoTen.setText(hoten);
        txt_SDT.setText(sdt);
 
        
        
    }//GEN-LAST:event_table_DSTKMouseClicked

    private void cbb_QuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_QuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_QuyenActionPerformed

    private void btn_SuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaTKActionPerformed
        // TODO add your handling code here:
        if(checkFullInfo_LoaiTV()){
            boolean bikhoa=false; 
            if(_dao.isExistTK(txt_MaTK.getText().trim()))
             {
                    if(!_dao.isExistTenDN(txt_TenDN.getText().trim())||_dao.getTenDNfromMaTK(txt_MaTK.getText().trim()).equals(txt_TenDN.getText().trim()))
                    {
                        String flag = (cbb_Quyen.getSelectedItem().toString().equals("Nhân viên"))?"user":"admin";
                        DTO_TaiKhoan tk =new DTO_TaiKhoan(
                                txt_MaTK.getText().trim(), txt_TenDN.getText(),txt_MK.getText(),txt_HoTen.getText(),txt_SDT.getText(),flag,bikhoa);
                            if(_dao.updateTaiKhoan(tk))
                                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
                            else
                                JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại!","Thông báo",JOptionPane.YES_OPTION);
                    }
                    else
                    JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
            
            }
            else
                JOptionPane.showMessageDialog(this, "Mã tài khoản sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
        loadDS();
    }//GEN-LAST:event_btn_SuaTKActionPerformed

     public boolean checkFullInfo_TK()
    {
        JTextField[] ds = new JTextField[]{txt_TenDN,txt_MaTK,txt_HoTen,txt_SDT};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    private void btn_ThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemTKActionPerformed
        // TODO add your handling code here:
       if(checkFullInfo_LoaiTV())
        {
            boolean bikhoa=false;
            if(!_dao.isExistTK(txt_MaTK.getText().trim()))
            {
                if(!_dao.isExistTenDN(txt_TenDN.getText().trim()))
                {
                String flag = (cbb_Quyen.getSelectedItem().toString().equals("Nhân viên"))?"user":"admin";
                    DTO_TaiKhoan tk =new DTO_TaiKhoan(
                    txt_MaTK.getText().trim(), txt_TenDN.getText(),txt_MK.getText(),txt_HoTen.getText(),txt_SDT.getText(),flag,bikhoa);
                    if(_dao.addTaiKhoan(tk))
                        JOptionPane.showMessageDialog(this, "Thêm mới tài khoản thành công!","Thông báo",JOptionPane.YES_OPTION);
                    else
                        JOptionPane.showMessageDialog(this, "Thêm mới tài khoản thất bại!","Thông báo",JOptionPane.YES_OPTION);
                }
                else
                JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã tài khoản đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
        loadDS();
       
    }//GEN-LAST:event_btn_ThemTKActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPanel1ComponentShown

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed

           // TODO add your handling code here:
          txt_TenDN.setText("");
          txt_HoTen.setText("");
          txt_MK.setText("");
          txt_SDT.setText("");
          txt_MaTK.setText("");
           loadDS(); 
          
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_KhoaMoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KhoaMoTKActionPerformed
        // TODO add your handling code here:
        if(table_DSTK.getSelectedRow()>0)
        {
            if(!quyen.equals("admin"))
            {
                if(flag)
                {
                    if(_dao.updateTrangThai(id, flag))
                        JOptionPane.showMessageDialog(this, "Mở khóa tài khoản thành công");
                    else
                        JOptionPane.showMessageDialog(this, "Mở khóa tài khoản thất bại");
                }
                else
                {
                    if(_dao.updateTrangThai(id, flag))
                        JOptionPane.showMessageDialog(this, "Khóa tài khoản thành công");
                    else
                        JOptionPane.showMessageDialog(this, "Khóa tài khoản thất bại");
                }
            }
            else
                JOptionPane.showMessageDialog(this, "Không được khóa tài khoản Admin");
            loadDS();
        }
        else
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản để thao tác");
    }//GEN-LAST:event_btn_KhoaMoTKActionPerformed

    private void txt_SDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDTKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_SDTKeyTyped

    private void btn_BoChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BoChonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BoChonActionPerformed
 public boolean checkFullInfo_LoaiTV()
    {
        JTextField[] ds = new JTextField[]{txt_TenDN,txt_MK,txt_HoTen,txt_SDT};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }

 public void phanquyen(){
     txt_HoTen.setEnabled(false);txt_MK.setEnabled(false);txt_MaTK.setEnabled(false);txt_SDT.setEnabled(false);txt_TenDN.setEnabled(false);
     btn_BoChon.setEnabled(false);btn_KhoaMoTK.setEnabled(false);btn_LamMoi.setEnabled(false);btn_SuaTK.setEnabled(false);btn_ThemTK.setEnabled(false);
 cbb_Quyen.setEnabled(false);
 }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BoChon;
    private javax.swing.JButton btn_CapNhatMK;
    private javax.swing.JButton btn_DoiMK;
    private javax.swing.JButton btn_KhoaMoTK;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_LamMoi_DMK;
    private javax.swing.JButton btn_SuaTK;
    private javax.swing.JButton btn_ThemTK;
    private javax.swing.JComboBox<String> cbb_Quyen;
    private javax.swing.JPasswordField field_pasword;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_HoTen;
    private javax.swing.JLabel lbl_MaTK;
    private javax.swing.JLabel lbl_Quyen;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TenDN;
    private javax.swing.JPanel pen_DMK;
    private javax.swing.JTable table_DSTK;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_MK;
    private javax.swing.JTextField txt_MaTK;
    private javax.swing.JPasswordField txt_MatKhaiMoi;
    private javax.swing.JPasswordField txt_MatKhauCu;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenDN;
    private javax.swing.JPasswordField txt_XacNhanMK;
    // End of variables declaration//GEN-END:variables
}
