package GUI;

import DAO.DAO_PhieuGG;
import DTO.DTO_PhieuGG;
import java.awt.Point;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_QLUuDai extends javax.swing.JPanel {

    DAO_PhieuGG _dao = new DAO_PhieuGG();
    DefaultTableModel modelDS = new DefaultTableModel();
    Vector data = new Vector();
    public Vector tblTitle = new Vector();
    /**
     * Creates new form panel_QLUuDai
     */
    public panel_QLUuDai(String maQ) {
        initComponents();
        if(maQ.trim().equals("user"))
            phanquyen();
        else
        {
        loadTitle();
        loadDS();
        }
    }

    public void loadTitle()
    {
        tblTitle.add("Mã giảm giá");
        tblTitle.add("Tên phiếu gg"); 
        tblTitle.add("Phần trăm gg");
        tblTitle.add("Ngày bắt đầu");
        tblTitle.add("Ngày kết thúc"); 
        modelDS.setColumnIdentifiers(tblTitle);
    }

    public void loadDS()
    {
        modelDS=new DefaultTableModel();
        modelDS.setColumnIdentifiers(tblTitle);
       List<DTO_PhieuGG> lst = _dao.getDS_PhieuGiamGia();
        for(DTO_PhieuGG i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaGiamGia);
            a.add(i.TenGiamGia);
            a.add(i.PhanTramGiamGia);
            a.add(i.NgayBD);
            a.add(i.NgayKT);
            data.add(a);
            modelDS.addRow(a);
        }
        table_DSGG.setModel(modelDS);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_MaGG = new javax.swing.JTextField();
        txt_TenGG = new javax.swing.JTextField();
        txt_NgayBD = new javax.swing.JTextField();
        btn_ThemGG = new javax.swing.JButton();
        btn_SuaGG = new javax.swing.JButton();
        btn_XoaGG = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Luu = new javax.swing.JButton();
        txt_PTGG = new javax.swing.JTextField();
        txt_NgayKT = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_DSGG = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Thông tin các phiếu giảm giá:");
        jLabel4.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Mã giảm giá:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Tên giảm giá:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Phần trăm giảm:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Ngày bắt đầu:");

        txt_MaGG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TenGG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_NgayBD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NgayBD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NgayBDKeyTyped(evt);
            }
        });

        btn_ThemGG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThemGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemGG.setText("Thêm phiếu GG");
        btn_ThemGG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemGG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ThemGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemGGActionPerformed(evt);
            }
        });

        btn_SuaGG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_SuaGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaGG.setText("Sửa phiếu GG");
        btn_SuaGG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaGGActionPerformed(evt);
            }
        });

        btn_XoaGG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_XoaGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negative.png"))); // NOI18N
        btn_XoaGG.setText("Xóa");
        btn_XoaGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaGGActionPerformed(evt);
            }
        });

        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi.setText(" Làm mới");
        btn_LamMoi.setActionCommand("Làm mới");
        btn_LamMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_Luu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        txt_PTGG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_PTGG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PTGGKeyTyped(evt);
            }
        });

        txt_NgayKT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NgayKT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NgayKTKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Ngày kết thúc:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addComponent(jLabel24)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_PTGG)
                            .addComponent(txt_TenGG)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_NgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(txt_NgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_MaGG)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_ThemGG)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SuaGG)
                        .addGap(18, 18, 18)
                        .addComponent(btn_XoaGG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_LamMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_PTGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_TenGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_NgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txt_NgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemGG)
                    .addComponent(btn_SuaGG)
                    .addComponent(btn_XoaGG)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_Luu))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        table_DSGG.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_DSGG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_DSGG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_DSGG.setRowHeight(35);
        table_DSGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DSGGMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_DSGG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_DSGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DSGGMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = table_DSGG.rowAtPoint(p);
        String magg = (String)modelDS.getValueAt(row, 0).toString();
        String tengg = (String)modelDS.getValueAt(row, 1).toString();
        String ptgg = (String)modelDS.getValueAt(row, 2).toString();
        String ngaybd = (String)modelDS.getValueAt(row, 3).toString();
        String ngaykt=(String)modelDS.getValueAt(row, 4).toString();
        
        txt_MaGG.setText(magg);
        txt_TenGG.setText(tengg);
        txt_PTGG.setText(ptgg);
        txt_NgayBD.setText(ngaybd);
        txt_NgayKT.setText(ngaykt);
    }//GEN-LAST:event_table_DSGGMouseClicked

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        txt_MaGG.setText("");
        txt_TenGG.setText("");
        txt_PTGG.setText("");
        txt_NgayBD.setText("");
        txt_NgayKT.setText("");
        btn_ThemGG.setEnabled(true);
        btn_XoaGG.setEnabled(true); btn_SuaGG.setEnabled(true);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_ThemGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemGGActionPerformed
        // TODO add your handling code here:
        if(checkFullInformation())
        {
            if(Integer.parseInt(txt_PTGG.getText().trim())>0 && Integer.parseInt(txt_PTGG.getText().trim())<100)
            {
                SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy");
                try { 
                    Date dateBD = sdf.parse(txt_NgayBD.getText().trim());
                    Date dateKT = sdf.parse(txt_NgayKT.getText().trim()); 
                    if(dateBD.compareTo(dateKT)<0)
                    {
                        if(!_dao.checkExistPrimarykey(txt_MaGG.getText().trim()))
                        {
                            VisibleButton_Luu(true, btn_ThemGG);
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Mã giảm giá đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
                    }
                    else
                            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc!","Thông báo",JOptionPane.YES_OPTION);

                } catch (ParseException ex) {
                      JOptionPane.showMessageDialog(this, "Ngày bắt đầu hoặc ngày kết thúc không hợp lệ!","Thông báo",JOptionPane.YES_OPTION);
                }
                
                
            }
            else
            JOptionPane.showMessageDialog(this, "Phần trăm giảm giá không hợp lệ!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_ThemGGActionPerformed

   
    private void btn_SuaGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaGGActionPerformed
        // TODO add your handling code here:
         if(checkFullInformation())
        {
            if(_dao.checkExistPrimarykey(txt_MaGG.getText().trim()))
            {
                VisibleButton_Luu(true, btn_SuaGG);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã giảm giá đang sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_SuaGGActionPerformed

    private void btn_XoaGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaGGActionPerformed
        // TODO add your handling code here:
        if(!_dao.checkExistForeignkey(txt_MaGG.getText().trim()))
            VisibleButton_Luu(true, btn_XoaGG);
        else
        {
            JOptionPane.showMessageDialog(this, "Mã giảm giá đang giữ khóa ngoại, không thể xóa!","Thông báo",JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btn_XoaGGActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
        if(btn_ThemGG.isEnabled())
        {
            //Thêm
            DTO_PhieuGG sp = new DTO_PhieuGG(txt_MaGG.getText(),txt_TenGG.getText(),Integer.parseInt(txt_PTGG.getText()),txt_NgayBD.getText(),txt_NgayKT.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_dao.addSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Thêm mã giảm giá thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, thêm thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            
        }
        else if(btn_XoaGG.isEnabled())
        {
            if(_dao.delSanPham(txt_MaGG.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Xóa giảm giá thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Mã giảm giá đang giữ khóa ngoại, xóa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            //Xóa
        }
        else if(btn_SuaGG.isEnabled())
        {
            DTO_PhieuGG sp = new DTO_PhieuGG(txt_MaGG.getText(),txt_TenGG.getText(),Integer.parseInt(txt_PTGG.getText()),txt_NgayBD.getText(),txt_NgayKT.getText());
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_dao.updateSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, sửa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDS();
         VisibleButton_Luu(false, btn_LamMoi);
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void txt_PTGGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PTGGKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_PTGGKeyTyped

    private void txt_NgayBDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NgayBDKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0' && evt.getKeyChar()!='-') evt.consume();
    }//GEN-LAST:event_txt_NgayBDKeyTyped

    private void txt_NgayKTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NgayKTKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0' && evt.getKeyChar()!='-') evt.consume();
    }//GEN-LAST:event_txt_NgayKTKeyTyped

    private void VisibleButton_Luu(boolean bool, JButton btn)
    {
        if(bool)
        {
            JButton[] ds = new JButton[]{btn_Luu};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
            ds = new JButton[]{btn_ThemGG,btn_SuaGG,btn_XoaGG};
            for(JButton i : ds)
            {
                if(i!=btn)
                    i.setEnabled(false);
            }
        }
        else
        {
            JButton[] ds = new JButton[]{btn_Luu};
            for(JButton i : ds)
            {
                i.setEnabled(false);
            }
            ds = new JButton[]{btn_ThemGG,btn_SuaGG,btn_XoaGG};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
        }
    }
    
    private boolean checkFullInformation()
    {
        JTextField[] ds = new JTextField[]{txt_MaGG,txt_TenGG,txt_PTGG,txt_NgayBD,txt_NgayKT};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    
    public void phanquyen(){
        txt_MaGG.setEnabled(false);txt_NgayBD.setEnabled(false);txt_NgayKT.setEnabled(false);txt_PTGG.setEnabled(false);txt_TenGG.setEnabled(false);
        btn_LamMoi.setEnabled(false);btn_Luu.setEnabled(false);btn_SuaGG.setEnabled(false);btn_ThemGG.setEnabled(false);btn_XoaGG.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_SuaGG;
    private javax.swing.JButton btn_ThemGG;
    private javax.swing.JButton btn_XoaGG;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_DSGG;
    private javax.swing.JTextField txt_MaGG;
    private javax.swing.JTextField txt_NgayBD;
    private javax.swing.JTextField txt_NgayKT;
    private javax.swing.JTextField txt_PTGG;
    private javax.swing.JTextField txt_TenGG;
    // End of variables declaration//GEN-END:variables
}
