package GUI;

import DAO.DAO_KeDat;
import DAO.DAO_NXB;
import DAO.DAO_SanPham;
import DAO.DAO_Tang;
import DAO.DAO_TheLoai;
import DAO.DAO_TimKiem;
import DTO.DTO_SanPham;
import DTO.DTO_TheLoai;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_TimKiemSP extends javax.swing.JPanel {

    /**
     * Creates new form panel_TimKiemSP
     */
    DAO_SanPham _dao = new DAO_SanPham();
    DAO_TimKiem _daoSearch = new DAO_TimKiem();
    DefaultTableModel modelDS = new DefaultTableModel();
    Vector data = new Vector();
     Vector tblTitle = new Vector();
    String path="";
    public panel_TimKiemSP() {
        initComponents();
        loadDS_TL();
        loadTitle();
        loadDS();
    }

    public void loadDS_TL()
    {
        ArrayList<DTO_TheLoai> cbb = DAO_TheLoai.listTheLoai();
         cbb_TheLoai.removeAllItems();
        for(DTO_TheLoai i : cbb)
        {
            cbb_TheLoai.addItem(i.TenTheLoai);
        }
    }
    
    public void loadTitle(){
       
        tblTitle.add("Mã sách");
        tblTitle.add("Tên sách"); 
        tblTitle.add("Tác giả");
        tblTitle.add("Số trang"); 
        tblTitle.add("Giá bán");
        tblTitle.add("Số lượng tồn"); 
        tblTitle.add("Mã thể loại");
        tblTitle.add("Mã NXB"); 
        tblTitle.add("Mã tầng");
        tblTitle.add("Mã kệ");  
    }
   public void loadDS()
    {
       data = new Vector();
       modelDS = new DefaultTableModel();
       modelDS.setColumnIdentifiers(tblTitle);
       List<DTO_SanPham> lst = _dao.getDS_Sach();
        for(DTO_SanPham i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaSach);
            a.add(i.TenSach);
            a.add(i.TacGia);
            a.add(i.SoTrang);
            a.add(i.GiaBan);
            a.add(i.SoLuongTon);
            a.add(i.MaTheLoai);
            a.add(i.MaNXB);
            a.add(i.MaTang);
            a.add(i.MaKe);
            data.add(a);
            modelDS.addRow(a);
        }
        
        table_QLSP.setModel(new DefaultTableModel( data,tblTitle));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_QLSP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_Tang4 = new javax.swing.JTextField();
        txt_Tang3 = new javax.swing.JTextField();
        txt_Tang1 = new javax.swing.JTextField();
        txt_Tang2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_MaSach = new javax.swing.JTextField();
        txt_TenSach = new javax.swing.JTextField();
        txt_TacGia = new javax.swing.JTextField();
        btn_TraCuu = new javax.swing.JButton();
        cbb_TheLoai = new javax.swing.JComboBox<>();
        btn_Reset = new javax.swing.JButton();
        rdo1 = new javax.swing.JRadioButton();
        rdo2 = new javax.swing.JRadioButton();
        rdo3 = new javax.swing.JRadioButton();
        rdo4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_KeE = new javax.swing.JTextField();
        txt_KeC = new javax.swing.JTextField();
        txt_KeB = new javax.swing.JTextField();
        txt_KeD = new javax.swing.JTextField();
        txt_KeA = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Tang_TimKiem = new javax.swing.JTextField();
        txt_Ke_TimKiem = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1756, 1058));

        table_QLSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_QLSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_QLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_QLSP.setRowHeight(35);
        table_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_QLSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_QLSP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Tầng đặt sách tìm kiếm:");
        jLabel4.setToolTipText("");

        txt_Tang4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_Tang4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Tang4.setText("TẦNG 4");
        txt_Tang4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txt_Tang4.setFocusable(false);
        txt_Tang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Tang4ActionPerformed(evt);
            }
        });

        txt_Tang3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_Tang3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Tang3.setText("TẦNG 3");
        txt_Tang3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txt_Tang3.setFocusable(false);

        txt_Tang1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_Tang1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Tang1.setText("TẦNG 1");
        txt_Tang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txt_Tang1.setFocusable(false);

        txt_Tang2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_Tang2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Tang2.setText("TẦNG 2");
        txt_Tang2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        txt_Tang2.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_Tang3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tang2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tang1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Tang4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(txt_Tang4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txt_Tang3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txt_Tang2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txt_Tang1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Thông tin sản phẩm:");
        jLabel3.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Mã sách:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tên sách:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Tác giả:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Thể loại:");

        txt_MaSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TenSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TenSach.setEnabled(false);

        txt_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TacGia.setEnabled(false);

        btn_TraCuu.setBackground(new java.awt.Color(102, 153, 255));
        btn_TraCuu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_TraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkTT.png"))); // NOI18N
        btn_TraCuu.setText("Tra cứu sách");
        btn_TraCuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraCuuActionPerformed(evt);
            }
        });

        cbb_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_TheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_TheLoai.setEnabled(false);
        cbb_TheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_TheLoaiActionPerformed(evt);
            }
        });

        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_Reset.setText("Làm mới");
        btn_Reset.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo1);
        rdo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdo1.setSelected(true);
        rdo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo2);
        rdo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo3);
        rdo3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo4);
        rdo4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_TacGia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenSach, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaSach, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_TheLoai, 0, 514, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(rdo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbb_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Kệ đặt sách tìm kiếm:");
        jLabel5.setToolTipText("");

        txt_KeE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_KeE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KeE.setText("E");
        txt_KeE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_KeE.setFocusable(false);

        txt_KeC.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_KeC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KeC.setText("C");
        txt_KeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_KeC.setFocusable(false);

        txt_KeB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_KeB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KeB.setText("B");
        txt_KeB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_KeB.setFocusable(false);

        txt_KeD.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_KeD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KeD.setText("D");
        txt_KeD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_KeD.setFocusable(false);

        txt_KeA.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txt_KeA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_KeA.setText("A");
        txt_KeA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        txt_KeA.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_KeA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_KeB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_KeC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_KeD, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_KeE, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_KeD, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_KeB, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_KeC, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_KeE, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_KeA, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Kết quả tìm kiếm:");
        jLabel6.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tầng:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Kệ đặt:");

        txt_Tang_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Tang_TimKiem.setFocusable(false);

        txt_Ke_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Ke_TimKiem.setFocusable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txt_Tang_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_Ke_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Tang_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txt_Ke_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraCuuActionPerformed
        // TODO add your handling code here:
        clearBackgroundColor();
        txt_Tang_TimKiem.setText("");
        txt_Ke_TimKiem.setText("");
        if(rdo1.isSelected())
        {
            if(txt_MaSach.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Hãy điền thông tin mã sách!","Thông báo",JOptionPane.YES_OPTION);
            }
            else{
                
                    DTO_SanPham _sach = _dao.getSachfromMa(txt_MaSach.getText().trim());
                    txt_Tang_TimKiem.setText(_dao.getTenTang(_sach.MaTang));
                    txt_Ke_TimKiem.setText(_dao.getTenKe(_sach.MaKe));
                    if(txt_Tang_TimKiem.getText().trim().equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "Mã sách không tồn tại!","Thông báo",JOptionPane.YES_OPTION);                    
                    }
                    else
                    {
                        data = new Vector();
                        modelDS = new DefaultTableModel();
                        modelDS.setColumnIdentifiers(tblTitle);
                        setBackgroundColor_Ke(_sach.MaKe.trim());
                        setBackgroundColor_Tang(_sach.MaTang.trim());
                        Vector a = new Vector();
                        a.add(_sach.MaSach);
                        a.add(_sach.TenSach);
                        a.add(_sach.TacGia);
                        a.add(_sach.SoTrang);
                        a.add(_sach.GiaBan);
                        a.add(_sach.SoLuongTon);
                        a.add(_sach.MaTheLoai);
                        a.add(_sach.MaNXB);
                        a.add(_sach.MaTang);
                        a.add(_sach.MaKe);  
                        data.add(a);
                        modelDS.addRow(a);
                    table_QLSP.setModel(new DefaultTableModel(data,tblTitle));
                    }
            }
        }
        if(rdo2.isSelected())
        {
            if(txt_TenSach.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Hãy điền thông tin tên sách!","Thông báo",JOptionPane.YES_OPTION);
            }
            else{
                    
                    DTO_SanPham _sach = _dao.getSach_from_TenSach(txt_TenSach.getText());
                    txt_Tang_TimKiem.setText(_dao.getTenTang(_sach.MaTang));
                    txt_Ke_TimKiem.setText(_dao.getTenKe(_sach.MaKe));
                    
                    if(txt_Tang_TimKiem.getText().trim().equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "Tên sách không tồn tại!","Thông báo",JOptionPane.YES_OPTION);                    
                    }
                    else
                    {
                        data = new Vector();
                        modelDS = new DefaultTableModel();
                    modelDS.setColumnIdentifiers(tblTitle);
                        setBackgroundColor_Ke(_sach.MaKe.trim());
                        setBackgroundColor_Tang(_sach.MaTang.trim());
                        Vector a = new Vector();
                        a.add(_sach.MaSach);
                        a.add(_sach.TenSach);
                        a.add(_sach.TacGia);
                        a.add(_sach.SoTrang);
                        a.add(_sach.GiaBan);
                        a.add(_sach.SoLuongTon);
                        a.add(_sach.MaTheLoai);
                        a.add(_sach.MaNXB);
                        a.add(_sach.MaTang);
                        a.add(_sach.MaKe);    
                        data.add(a);
                        modelDS.addRow(a);
                    table_QLSP.setModel(new DefaultTableModel(data,tblTitle));
                    }
            }
        }
        if(rdo3.isSelected())
        {
            if(txt_TacGia.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Hãy điền thông tin tác giả!","Thông báo",JOptionPane.YES_OPTION);
            }
            else{
                    modelDS = new DefaultTableModel();
                    modelDS.setColumnIdentifiers(tblTitle);
                    ArrayList<DTO_SanPham> ds = _daoSearch.getDS_fromTacGia(txt_TacGia.getText());
                    Vector _vt = new Vector();
                    for(DTO_SanPham i : ds)
                    {
                        Vector a = new Vector();
                        a.add(i.MaSach);
                        a.add(i.TenSach);
                        a.add(i.TacGia);
                        a.add(i.SoTrang);
                        a.add(i.GiaBan);
                        a.add(i.SoLuongTon);
                        a.add(i.MaTheLoai);
                        a.add(i.MaNXB);
                        a.add(i.MaTang);
                        a.add(i.MaKe);
                        _vt.add(a);
                        modelDS.addRow(a);
                    }
                    table_QLSP.setModel(new DefaultTableModel(_vt,tblTitle));
                    
            }
        }
        if(rdo4.isSelected())
        {
                    modelDS = new DefaultTableModel();
                    modelDS.setColumnIdentifiers(tblTitle);
                    ArrayList<DTO_SanPham> ds = _daoSearch.getDS_fromTheLoai(
                            _dao.getMaTheLoai(cbb_TheLoai.getSelectedItem().toString())
                    );
                    Vector _vt = new Vector();
                    for(DTO_SanPham i : ds)
                    {
                        Vector a = new Vector();
                        a.add(i.MaSach);
                        a.add(i.TenSach);
                        a.add(i.TacGia);
                        a.add(i.SoTrang);
                        a.add(i.GiaBan);
                        a.add(i.SoLuongTon);
                        a.add(i.MaTheLoai);
                        a.add(i.MaNXB);
                        a.add(i.MaTang);
                        a.add(i.MaKe);
                        _vt.add(a);
                        modelDS.addRow(a);
                    }
                    table_QLSP.setModel(new DefaultTableModel(_vt,tblTitle));
        }
    }//GEN-LAST:event_btn_TraCuuActionPerformed

    private void cbb_TheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_TheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_TheLoaiActionPerformed

    private void rdo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo1ActionPerformed
        // TODO add your handling code here:
        txt_TenSach.setEnabled(false);
        txt_TacGia.setEnabled(false);
        cbb_TheLoai.setEnabled(false);
        txt_MaSach.setEnabled(true);
    }//GEN-LAST:event_rdo1ActionPerformed

    private void rdo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo2ActionPerformed
        // TODO add your handling code here:
        txt_TenSach.setEnabled(true);
        txt_TacGia.setEnabled(false);
        cbb_TheLoai.setEnabled(false);
        txt_MaSach.setEnabled(false);
    }//GEN-LAST:event_rdo2ActionPerformed

    private void rdo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo3ActionPerformed
        // TODO add your handling code here:
        txt_TenSach.setEnabled(false);
        txt_TacGia.setEnabled(true);
        cbb_TheLoai.setEnabled(false);
        txt_MaSach.setEnabled(false);
    }//GEN-LAST:event_rdo3ActionPerformed

    private void rdo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo4ActionPerformed
        // TODO add your handling code here:
        txt_TenSach.setEnabled(false);
        txt_TacGia.setEnabled(false);
        cbb_TheLoai.setEnabled(true);
        txt_MaSach.setEnabled(false);
    }//GEN-LAST:event_rdo4ActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        txt_TacGia.setText("");
        txt_TenSach.setText("");
        txt_MaSach.setText("");
        cbb_TheLoai.setSelectedIndex(0);
        
        txt_MaSach.setEnabled(true);
        txt_TenSach.setEnabled(false);
        txt_TacGia.setEnabled(false);
        cbb_TheLoai.setEnabled(false);
        rdo1.setSelected(true);
        clearBackgroundColor();
        txt_Tang_TimKiem.setText("");
        txt_Ke_TimKiem.setText("");
        loadDS();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void table_QLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_QLSPMouseClicked
        // TODO add your handling code here:
        clearBackgroundColor();
        Point p = evt.getPoint();
        int row = table_QLSP.rowAtPoint(p);
        String maTang = (String)modelDS.getValueAt(row, 8).toString().trim();
        String maKe = (String)modelDS.getValueAt(row, 9).toString().trim();
        
        txt_Tang_TimKiem.setText(_dao.getTenTang(maTang.trim()));
        txt_Ke_TimKiem.setText(_dao.getTenKe(maKe.trim()));
        setBackgroundColor_Ke(maKe);
        setBackgroundColor_Tang(maTang);
    }//GEN-LAST:event_table_QLSPMouseClicked

    private void txt_Tang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Tang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Tang4ActionPerformed

    private void setBackgroundColor_Tang(String _ma)
    {
        if(_ma.equals("T01"))
            txt_Tang1.setBackground(Color.cyan);
        if(_ma.equals("T02"))
            txt_Tang2.setBackground(Color.cyan);
        if(_ma.equals("T03"))
            txt_Tang3.setBackground(Color.cyan);
        if(_ma.equals("T04"))
            txt_Tang4.setBackground(Color.cyan);
    }
    
    private void setBackgroundColor_Ke(String _ma)
    {
        if(_ma.equals("K01"))
            txt_KeA.setBackground(Color.orange);
        if(_ma.equals("K02"))
            txt_KeB.setBackground(Color.orange);
        if(_ma.equals("K03"))
            txt_KeC.setBackground(Color.orange);
        if(_ma.equals("K04"))
            txt_KeD.setBackground(Color.orange);
        if(_ma.equals("K05"))
            txt_KeE.setBackground(Color.orange);
    }
    
    private void clearBackgroundColor()
    {
        JTextField[] ds = new JTextField[]{txt_KeA,txt_KeC,txt_KeB,txt_KeD,txt_KeE,txt_Tang1,txt_Tang2,txt_Tang3,txt_Tang4};
        for(JTextField i : ds)
            i.setBackground(Color.white);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_TraCuu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbb_TheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo1;
    private javax.swing.JRadioButton rdo2;
    private javax.swing.JRadioButton rdo3;
    private javax.swing.JRadioButton rdo4;
    private javax.swing.JTable table_QLSP;
    private javax.swing.JTextField txt_KeA;
    private javax.swing.JTextField txt_KeB;
    private javax.swing.JTextField txt_KeC;
    private javax.swing.JTextField txt_KeD;
    private javax.swing.JTextField txt_KeE;
    private javax.swing.JTextField txt_Ke_TimKiem;
    private javax.swing.JTextField txt_MaSach;
    private javax.swing.JTextField txt_TacGia;
    private javax.swing.JTextField txt_Tang1;
    private javax.swing.JTextField txt_Tang2;
    private javax.swing.JTextField txt_Tang3;
    private javax.swing.JTextField txt_Tang4;
    private javax.swing.JTextField txt_Tang_TimKiem;
    private javax.swing.JTextField txt_TenSach;
    // End of variables declaration//GEN-END:variables
}
