package GUI;

import DAO.DAO_ChiTietHDB;
import DAO.DAO_Sach;
import DTO.DTO_Sach;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.DAO_HoaDonKho;
import DAO.DAO_SanPham;
import DAO.DBConnection;
import DTO.DTO_ChiTietHoaDonBan;
import DTO.DTO_HoaDonNhap;
import java.awt.Point;
import java.awt.TextField;
import java.time.LocalDate;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_QLKhoHang extends javax.swing.JPanel {

    DAO_HoaDonKho hdk=new DAO_HoaDonKho();
    DAO_Sach _dao=new DAO_Sach();
    DefaultTableModel modelDS = new DefaultTableModel();
    DefaultTableModel modelKH = new DefaultTableModel();
    Vector data = new Vector();
    public Vector tblTitle = new Vector();
    public Vector tblTitleNhap = new Vector(); 
    String id="";
    /**
     * Creates new form panel_QLKhoHang
     */
    String matk="";
    public panel_QLKhoHang(String ma) {
        initComponents();
        matk = ma;
        loadTitle();
        loadTitleKhoHang();
        loadDSKhoHang();
        
    }
    
    public void loadTitle()
    {
 
        tblTitle.add("Mã sách");
        tblTitle.add("Tên sách"); 
        tblTitle.add("Tác giả");
        tblTitle.add("Giá bán");
        tblTitle.add("Số lượng tồn"); 
        modelDS.setColumnIdentifiers(tblTitle);
        table_QLSP.setModel(modelDS); 
    }
    public void loadTitleKhoHang()
    {
        tblTitleNhap.add("Số HDK");
        tblTitleNhap.add("Số lượng");
        tblTitleNhap.add("Tổng tiền");
        tblTitleNhap.add("Ngày lập");
        tblTitleNhap.add("Ghi chú");
        tblTitleNhap.add("Mã sách");
        tblTitleNhap.add("Mã TK");
        tblTitleNhap.add("Mã loại HD");
        modelKH.setColumnIdentifiers(tblTitleNhap);
        table_QLHD.setModel(modelKH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void loadDSKhoHang()
    {
        modelKH = new DefaultTableModel();
        modelKH.setColumnIdentifiers(tblTitleNhap);
        ArrayList<DTO_HoaDonNhap> lst = hdk.getDS_HDKho();
        for(DTO_HoaDonNhap i : lst)
        {
            Vector a = new Vector();
            a.add(i.soHD);a.add(i.soluong);a.add(i.tongtien);a.add(i.ngaylap);a.add(i.ghichu);a.add(i.masach);a.add(i.mataikhoan);a.add(i.maloaihd);
            modelKH.addRow(a);
        }
        table_QLHD.setModel(modelKH);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_QLSP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_QLHD = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_SL_GanHet = new javax.swing.JTextField();
        btn_TraCuu = new javax.swing.JButton();
        btn_LamMoi_TC = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbb_NhapXuat = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        txt_TongTien = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_NgayLap = new javax.swing.JTextField();
        txt_GhiChu = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_MaSach = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_SoHD = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btn_TraCuu_NX = new javax.swing.JButton();
        btn_XuatHD = new javax.swing.JButton();
        btn_NhapXuat = new javax.swing.JButton();
        btn_LamMoi_NX = new javax.swing.JButton();
        btn_TraCuu_NX1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        table_QLSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_QLSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_QLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_QLSP.setRowHeight(35);
        jScrollPane1.setViewportView(table_QLSP);

        table_QLHD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_QLHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_QLHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_QLHD.setRowHeight(35);
        table_QLHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_QLHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_QLHD);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Tra cứu sách gần hết:");
        jLabel3.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Nhập số lượng tồn nhỏ hơn:");

        txt_SL_GanHet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SL_GanHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SL_GanHetActionPerformed(evt);
            }
        });
        txt_SL_GanHet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SL_GanHetKeyTyped(evt);
            }
        });

        btn_TraCuu.setBackground(new java.awt.Color(102, 153, 255));
        btn_TraCuu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TraCuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkTT.png"))); // NOI18N
        btn_TraCuu.setText("Tra cứu");
        btn_TraCuu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TraCuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraCuuActionPerformed(evt);
            }
        });

        btn_LamMoi_TC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LamMoi_TC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_TC.setText("Làm mới");
        btn_LamMoi_TC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_LamMoi_TC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_TCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(txt_SL_GanHet, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_TraCuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_LamMoi_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_SL_GanHet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_LamMoi_TC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TraCuu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Nhập hàng/Xuất hàng:");
        jLabel4.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Nhập hàng/Xuất hàng:");

        cbb_NhapXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_NhapXuat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhập hàng", "Xuất hàng" }));
        cbb_NhapXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_NhapXuatActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Nhập số lượng:");

        txt_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SoLuongKeyTyped(evt);
            }
        });

        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TongTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TongTienKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Tổng tiền:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Ngày lập:");

        txt_NgayLap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NgayLap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NgayLapKeyTyped(evt);
            }
        });

        txt_GhiChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Ghi chú:");

        txt_MaSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Mã sách N/X:");

        txt_SoHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SoHD.setText("Automatic");
        txt_SoHD.setFocusable(false);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Số hóa đơn:");

        btn_TraCuu_NX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TraCuu_NX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkTT.png"))); // NOI18N
        btn_TraCuu_NX.setText("Tra cứu");
        btn_TraCuu_NX.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TraCuu_NX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraCuu_NXActionPerformed(evt);
            }
        });

        btn_XuatHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XuatHD.setForeground(new java.awt.Color(51, 51, 51));
        btn_XuatHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        btn_XuatHD.setText("Xuất HD");
        btn_XuatHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_XuatHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatHDActionPerformed(evt);
            }
        });

        btn_NhapXuat.setBackground(new java.awt.Color(102, 153, 255));
        btn_NhapXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_NhapXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_NhapXuat.setText("Nhập/Xuất");
        btn_NhapXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_NhapXuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_NhapXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhapXuatActionPerformed(evt);
            }
        });

        btn_LamMoi_NX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LamMoi_NX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi_NX.setText("Làm mới");
        btn_LamMoi_NX.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_LamMoi_NX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi_NXActionPerformed(evt);
            }
        });

        btn_TraCuu_NX1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TraCuu_NX1.setText("Hôm nay");
        btn_TraCuu_NX1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_TraCuu_NX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TraCuu_NX1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_TongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_SoLuong)
                        .addComponent(txt_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txt_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_TraCuu_NX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbb_NhapXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_SoHD)
                        .addComponent(txt_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_TraCuu_NX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_XuatHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_NhapXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_LamMoi_NX, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbb_NhapXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi_NX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_SoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_TraCuu_NX1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_GhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_XuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TraCuu_NX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_NhapXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TraCuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraCuuActionPerformed
        // TODO add your handling code here:
        if(txt_SL_GanHet.getText().trim().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Hãy điền thông tin số lượng sách tồn cần tra cứu!","Thông báo",JOptionPane.YES_OPTION);
        }
        else{
               int slTon=Integer.parseInt(txt_SL_GanHet.getText().trim());
               ArrayList<DTO_Sach> tv = _dao.getDS_Sach_SLT(slTon);
               Vector _a = new Vector();
               for(DTO_Sach i : tv)
               {
                Vector a = new Vector();
                a.add(i.masach);
                a.add(i.tensach);
                a.add(i.tacgia);
                a.add(i.giaban);
                a.add(i.soluongton);
                modelDS.addRow(a);
                _a.add(a);
               }
                   table_QLSP.setModel(new DefaultTableModel(_a, tblTitle));
        }
    }//GEN-LAST:event_btn_TraCuuActionPerformed

    private void btn_LamMoi_TCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_TCActionPerformed
        // TODO add your handling code here:
        txt_SL_GanHet.setText("");
    }//GEN-LAST:event_btn_LamMoi_TCActionPerformed

    private void cbb_NhapXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_NhapXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_NhapXuatActionPerformed

    private void btn_TraCuu_NXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraCuu_NXActionPerformed
        // TODO add your handling code here:
        String ma;
        if(cbb_NhapXuat.getSelectedItem().toString()=="Nhập hàng")
        {
            ma="HDNhapKho";
            ArrayList<DTO_HoaDonNhap> lst=hdk.getDS_from_MaLoaiHD(ma);
            
            modelKH = new DefaultTableModel();
            modelKH.setColumnIdentifiers(tblTitleNhap);
            for(DTO_HoaDonNhap hd : lst)
            {
                Vector a=new Vector();
                a.add(hd.soHD);
                a.add(hd.soluong);
                a.add(hd.tongtien);
                a.add(hd.ngaylap);
                a.add(hd.ghichu);
                a.add(hd.masach);
                a.add(hd.mataikhoan);
                a.add(hd.maloaihd);
                modelKH.addRow(a);
            }
            table_QLHD.setModel(modelKH);
        }
        else
        {
            ma="HDXuatKho";
             ArrayList<DTO_HoaDonNhap> lst=hdk.getDS_from_MaLoaiHD(ma);
            
            modelKH = new DefaultTableModel();
            modelKH.setColumnIdentifiers(tblTitleNhap);
            for(DTO_HoaDonNhap hd : lst)
            {
                Vector a=new Vector();
                a.add(hd.soHD);
                a.add(hd.soluong);
                a.add(hd.tongtien);
                a.add(hd.ngaylap);
                a.add(hd.ghichu);
                a.add(hd.masach);
                a.add(hd.mataikhoan);
                a.add(hd.maloaihd);
                modelKH.addRow(a);
            }
            table_QLHD.setModel(modelKH);
        }
        
    }//GEN-LAST:event_btn_TraCuu_NXActionPerformed

    private void btn_NhapXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhapXuatActionPerformed
        // TODO add your handling code here:
        if(checkFullInformation())
        {
            if(cbb_NhapXuat.getSelectedIndex()>=0)
            {
                if(DAO_SanPham.checkExistPrimarykey(txt_MaSach.getText().trim()))
                {
                    //Ok
                    if(cbb_NhapXuat.getSelectedIndex()==0)
                    {
                        //Nhập hàng
                        String ghichu = (txt_GhiChu.getText().trim().equals(""))?"Không có":txt_GhiChu.getText().trim();
                        DTO_HoaDonNhap hd = new DTO_HoaDonNhap("X", Integer.parseInt(txt_SoLuong.getText().trim()),
                                Integer.parseInt(txt_TongTien.getText().trim()),
                                txt_NgayLap.getText().trim(), ghichu, txt_MaSach.getText().trim(),
                                matk, "HDNhapKho");
                        if(hdk.addHoaDonKho(hd))
                        {
                            //Thành công
                            //Cập nhật số lượng nhập kho
                            hdk.updateSoLuongTon(hd.masach, hd.soluong);                            
                            JOptionPane.showMessageDialog(this, "Đã nhập kho hàng thành công!");
                             loadDSKhoHang();
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Ngày nhập kho không đúng định dạng!");
                       
                    }
                    else
                    {
                        //Xuất kho
                        if(DAO_Sach.checkSLTonDu(txt_MaSach.getText().trim(), Integer.parseInt(txt_SoLuong.getText().trim())))
                        {
                            String ghichu = (txt_GhiChu.getText().trim().equals(""))?"Không có":txt_GhiChu.getText().trim();
                            DTO_HoaDonNhap hd = new DTO_HoaDonNhap("X", Integer.parseInt(txt_SoLuong.getText().trim()),
                                    Integer.parseInt(txt_TongTien.getText().trim()),
                                    txt_NgayLap.getText().trim(), ghichu, txt_MaSach.getText().trim(),
                                    matk, "HDXuatKho");
                            if(hdk.addHoaDonKho(hd))
                            {
                                //Thành công
                                //Cập nhật số lượng nhập kho
                                hdk.updateSoLuongTon_XuatKho(hd.masach, hd.soluong);                            
                                JOptionPane.showMessageDialog(this, "Đã xuất kho hàng thành công!");
                                 loadDSKhoHang();
                            }
                            else
                                JOptionPane.showMessageDialog(this, "Ngày xuất kho không đúng định dạng!");
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Số lượng trong kho không đủ xuất!");
                    }
                }
                else
                    JOptionPane.showMessageDialog(this, "Mã sách xuất kho không hợp lệ!"); 
            }
            else
              JOptionPane.showMessageDialog(this, "Vui lòng chọn loại hóa đơn!");  
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_NhapXuatActionPerformed

    private void btn_TraCuu_NX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TraCuu_NX1ActionPerformed
        // TODO add your handling code here:
        LocalDate currentdate = LocalDate.now();
        txt_NgayLap.setText(currentdate.getMonthValue()+"/"+currentdate.getDayOfMonth()+"/"+currentdate.getYear());
    }//GEN-LAST:event_btn_TraCuu_NX1ActionPerformed

    private void txt_SoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoLuongKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_SoLuongKeyTyped

    private void txt_TongTienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TongTienKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_TongTienKeyTyped

    private void btn_LamMoi_NXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi_NXActionPerformed
        // TODO add your handling code here:
        JTextField[] lst = new JTextField[]{txt_MaSach, txt_NgayLap,txt_SoLuong,txt_TongTien,txt_GhiChu};
        for(JTextField i : lst)
            i.setText("");
        cbb_NhapXuat.setSelectedIndex(0);
        loadDSKhoHang();
    }//GEN-LAST:event_btn_LamMoi_NXActionPerformed

    private void btn_XuatHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatHDActionPerformed
        // TODO add your handling code here:
         try
    {
        Hashtable map = new Hashtable();
        JasperReport rp=JasperCompileManager.compileReport("src/main/java/REPORT/rp_KhoHang.jrxml");
        map.put("SoHDK", id);
        DBConnection cn  = new DBConnection();
        JasperPrint print = JasperFillManager.fillReport(rp, map, cn.getCn());
        JasperViewer.viewReport(print,false);
        
        }
       catch(JRException ex)
        {
            Logger.getLogger(penel_QLHoaDon.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        
        
        
    }//GEN-LAST:event_btn_XuatHDActionPerformed

    private void table_QLHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_QLHDMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = table_QLHD.rowAtPoint(p);
        String sohd = (String)modelKH.getValueAt(row, 0).toString();
        id = sohd;
        
    }//GEN-LAST:event_table_QLHDMouseClicked

    private void txt_SL_GanHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SL_GanHetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SL_GanHetActionPerformed

    private void txt_SL_GanHetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SL_GanHetKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_SL_GanHetKeyTyped

    private void txt_NgayLapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NgayLapKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0' && evt.getKeyChar()!='-') evt.consume();
    }//GEN-LAST:event_txt_NgayLapKeyTyped

    public boolean checkFullInformation()
    {
        JTextField[] lst = new JTextField[]{txt_MaSach, txt_NgayLap,txt_SoLuong,txt_TongTien};
        for(JTextField i : lst)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi_NX;
    private javax.swing.JButton btn_LamMoi_TC;
    private javax.swing.JButton btn_NhapXuat;
    private javax.swing.JButton btn_TraCuu;
    private javax.swing.JButton btn_TraCuu_NX;
    private javax.swing.JButton btn_TraCuu_NX1;
    private javax.swing.JButton btn_XuatHD;
    private javax.swing.JComboBox<String> cbb_NhapXuat;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_QLHD;
    private javax.swing.JTable table_QLSP;
    private javax.swing.JTextField txt_GhiChu;
    private javax.swing.JTextField txt_MaSach;
    private javax.swing.JTextField txt_NgayLap;
    private javax.swing.JTextField txt_SL_GanHet;
    private javax.swing.JTextField txt_SoHD;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
