package GUI;


import DAO.DAO_Sach;
import DAO.DAO_HoaDonBan;
import DAO.DAO_PhieuGG;
import DAO.DAO_ThanhVien;
import DAO.DBConnection;
import DTO.DTO_ChiTietHoaDon;
import DTO.DTO_ChiTietHoaDonBan;
import java.awt.Color;
import javax.swing.JOptionPane;
import DTO.DTO_Sach;
import DTO.DTO_HoaDonBan;
import DTO.DTO_PhieuGG;
import DTO.DTO_ThanhVien;
import java.awt.Point;
import java.net.URL;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_BanSach extends javax.swing.JPanel {

    /**
     * Creates new form panel_BanSach
     */
    DefaultTableModel model = new DefaultTableModel();
    Vector title = new Vector();
    DAO_Sach daoSach = new DAO_Sach();
    DAO_ThanhVien daoTV = new DAO_ThanhVien();
    DAO_PhieuGG daoGG = new DAO_PhieuGG();
    DAO_HoaDonBan daoHDB = new DAO_HoaDonBan();
    ArrayList<DTO_ChiTietHoaDon> lstCTHD = new ArrayList<DTO_ChiTietHoaDon>();
    int ggTV=0, ggVC=0, tongtien=0;
    String maTK="";
    public panel_BanSach(String _ma) {
        initComponents();
        maTK = _ma;
        spin_SoLuong.setValue(1);
        loadTitle();
        jpn_ttt.setEnabled(false); jpn_uudai.setEnabled(false);
    }
    
    public void loadTitle()
    {
        title.add("Mã sách");
        title.add("Tên sách");
        title.add("Ngày lập");
        title.add("Người lập");            
        title.add("Giá bán");
        title.add("Số lượng");
        title.add("Tổng tiền");
        model.setColumnIdentifiers(title);
        table_QLBanHang.setModel(model); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup_BanSachThanhVien = new javax.swing.ButtonGroup();
        btngroup_BanSachMaGG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_QLBanHang = new javax.swing.JTable();
        img_sp_mua = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_MaSach = new javax.swing.JTextField();
        txt_TenSach = new javax.swing.JTextField();
        txt_TacGia = new javax.swing.JTextField();
        txt_TheLoai = new javax.swing.JTextField();
        txt_GiaBan = new javax.swing.JTextField();
        txt_NXB = new javax.swing.JTextField();
        btn_CheckSP = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        spin_SoLuong = new javax.swing.JSpinner();
        btn_fresh = new javax.swing.JButton();
        btn_AddToList = new javax.swing.JButton();
        btn_RemoveAllList = new javax.swing.JButton();
        jpn_uudai = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_TV_SDT = new javax.swing.JTextField();
        rdo_TV_Co = new javax.swing.JRadioButton();
        rdo_TV_Khong = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        rdo_GG_Khong = new javax.swing.JRadioButton();
        rdo_GG_Co = new javax.swing.JRadioButton();
        txt_MaGG = new javax.swing.JTextField();
        btn_CheckGG = new javax.swing.JButton();
        btn_CheckTV = new javax.swing.JButton();
        jpn_ttt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_ThanhToan = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_TTT_GGTV = new javax.swing.JLabel();
        lbl_TTT_GGVC = new javax.swing.JLabel();
        lbl_TTT_TongGiam = new javax.swing.JLabel();
        lbl_TTT_TongTien = new javax.swing.JLabel();
        lbl_TTT_ThanhTien = new javax.swing.JLabel();
        btn_XuatHD = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setRequestFocusEnabled(false);

        table_QLBanHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_QLBanHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_QLBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_QLBanHang.setRowHeight(35);
        table_QLBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_QLBanHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_QLBanHang);

        img_sp_mua.setBackground(new java.awt.Color(255, 153, 102));
        img_sp_mua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loadingPic.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Thông tin sản phẩm:");
        jLabel3.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Mã sách:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tên sách:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Tác giả:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Thể loại:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("NXB:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Giá bán:");

        txt_MaSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_MaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaSachActionPerformed(evt);
            }
        });

        txt_TenSach.setEditable(false);
        txt_TenSach.setBackground(new java.awt.Color(247, 246, 246));
        txt_TenSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TenSach.setFocusable(false);

        txt_TacGia.setEditable(false);
        txt_TacGia.setBackground(new java.awt.Color(247, 246, 246));
        txt_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TacGia.setFocusable(false);

        txt_TheLoai.setEditable(false);
        txt_TheLoai.setBackground(new java.awt.Color(247, 246, 246));
        txt_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TheLoai.setFocusable(false);

        txt_GiaBan.setEditable(false);
        txt_GiaBan.setBackground(new java.awt.Color(247, 246, 246));
        txt_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_GiaBan.setFocusable(false);

        txt_NXB.setEditable(false);
        txt_NXB.setBackground(new java.awt.Color(247, 246, 246));
        txt_NXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NXB.setFocusable(false);

        btn_CheckSP.setBackground(new java.awt.Color(0, 153, 255));
        btn_CheckSP.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_CheckSP.setText("Kiểm tra");
        btn_CheckSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckSPActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Số lượng mua:");

        spin_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spin_SoLuong.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                spin_SoLuongHierarchyChanged(evt);
            }
        });
        spin_SoLuong.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spin_SoLuongAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        spin_SoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_SoLuongStateChanged(evt);
            }
        });
        spin_SoLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spin_SoLuongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spin_SoLuongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spin_SoLuongMousePressed(evt);
            }
        });
        spin_SoLuong.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                spin_SoLuongInputMethodTextChanged(evt);
            }
        });
        spin_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spin_SoLuongKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spin_SoLuongKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spin_SoLuongKeyTyped(evt);
            }
        });
        spin_SoLuong.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                spin_SoLuongVetoableChange(evt);
            }
        });

        btn_fresh.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_fresh.setText("Làm mới");
        btn_fresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_freshActionPerformed(evt);
            }
        });

        btn_AddToList.setBackground(new java.awt.Color(0, 153, 255));
        btn_AddToList.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_AddToList.setText("Thêm ");
        btn_AddToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddToListActionPerformed(evt);
            }
        });

        btn_RemoveAllList.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_RemoveAllList.setText("Xóa hết");
        btn_RemoveAllList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveAllListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_MaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(txt_TenSach))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_fresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_CheckSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(txt_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txt_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TheLoai))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24))
                            .addComponent(btn_AddToList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spin_SoLuong)
                            .addComponent(btn_RemoveAllList, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CheckSP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_fresh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txt_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(spin_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RemoveAllList, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AddToList, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpn_uudai.setBackground(new java.awt.Color(255, 255, 255));
        jpn_uudai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpn_uudai.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Thông tin ưu đãi:");
        jLabel1.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Ưu đãi thành viên:");

        txt_TV_SDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_TV_SDT.setText("Nhập số điện thoại...");
        txt_TV_SDT.setEnabled(false);
        txt_TV_SDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_TV_SDTMouseClicked(evt);
            }
        });
        txt_TV_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TV_SDTActionPerformed(evt);
            }
        });
        txt_TV_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TV_SDTKeyTyped(evt);
            }
        });

        btngroup_BanSachThanhVien.add(rdo_TV_Co);
        rdo_TV_Co.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_TV_Co.setText("Có");
        rdo_TV_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_TV_CoActionPerformed(evt);
            }
        });

        btngroup_BanSachThanhVien.add(rdo_TV_Khong);
        rdo_TV_Khong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_TV_Khong.setSelected(true);
        rdo_TV_Khong.setText("Không");
        rdo_TV_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_TV_KhongActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Ưu đãi phiếu giảm giá:");

        btngroup_BanSachMaGG.add(rdo_GG_Khong);
        rdo_GG_Khong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_GG_Khong.setSelected(true);
        rdo_GG_Khong.setText("Không");
        rdo_GG_Khong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_GG_KhongActionPerformed(evt);
            }
        });

        btngroup_BanSachMaGG.add(rdo_GG_Co);
        rdo_GG_Co.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_GG_Co.setText("Có");
        rdo_GG_Co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_GG_CoActionPerformed(evt);
            }
        });

        txt_MaGG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_MaGG.setText("Nhập mã giảm giá...");
        txt_MaGG.setEnabled(false);
        txt_MaGG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_MaGGMouseClicked(evt);
            }
        });

        btn_CheckGG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_CheckGG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkTT.png"))); // NOI18N
        btn_CheckGG.setText("Kiểm tra thông tin");
        btn_CheckGG.setEnabled(false);
        btn_CheckGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckGGActionPerformed(evt);
            }
        });

        btn_CheckTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_CheckTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/checkTT.png"))); // NOI18N
        btn_CheckTV.setText("Kiểm tra thông tin");
        btn_CheckTV.setEnabled(false);
        btn_CheckTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_uudaiLayout = new javax.swing.GroupLayout(jpn_uudai);
        jpn_uudai.setLayout(jpn_uudaiLayout);
        jpn_uudaiLayout.setHorizontalGroup(
            jpn_uudaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_uudaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_uudaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_CheckGG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TV_SDT)
                    .addComponent(txt_MaGG)
                    .addGroup(jpn_uudaiLayout.createSequentialGroup()
                        .addGroup(jpn_uudaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel22)
                            .addGroup(jpn_uudaiLayout.createSequentialGroup()
                                .addComponent(rdo_TV_Khong)
                                .addGap(30, 30, 30)
                                .addComponent(rdo_TV_Co))
                            .addGroup(jpn_uudaiLayout.createSequentialGroup()
                                .addComponent(rdo_GG_Khong)
                                .addGap(35, 35, 35)
                                .addComponent(rdo_GG_Co))
                            .addComponent(jLabel23))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_CheckTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpn_uudaiLayout.setVerticalGroup(
            jpn_uudaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_uudaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jpn_uudaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_TV_Co)
                    .addComponent(rdo_TV_Khong))
                .addGap(18, 18, 18)
                .addComponent(txt_TV_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CheckTV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jpn_uudaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_GG_Khong)
                    .addComponent(rdo_GG_Co))
                .addGap(18, 18, 18)
                .addComponent(txt_MaGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_CheckGG, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpn_ttt.setBackground(new java.awt.Color(255, 255, 255));
        jpn_ttt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tổng thanh toán:");
        jLabel2.setToolTipText("");

        btn_ThanhToan.setBackground(new java.awt.Color(51, 153, 255));
        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_ThanhToan.setText("HOÀN TẤT THANH TOÁN");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_Reset.setForeground(new java.awt.Color(51, 51, 51));
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_Reset.setText("      Làm mới");
        btn_Reset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Giảm giá thành viên:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Giảm giá voucher:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tổng tiền:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tổng (%) giảm:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Thành tiền:");

        lbl_TTT_GGTV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TTT_GGTV.setText("0");

        lbl_TTT_GGVC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TTT_GGVC.setText("0");

        lbl_TTT_TongGiam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TTT_TongGiam.setText("0");

        lbl_TTT_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TTT_TongTien.setText("0");

        lbl_TTT_ThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lbl_TTT_ThanhTien.setForeground(new java.awt.Color(255, 0, 51));
        lbl_TTT_ThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_TTT_ThanhTien.setText("0");

        btn_XuatHD.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_XuatHD.setForeground(new java.awt.Color(51, 51, 51));
        btn_XuatHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        btn_XuatHD.setText("    Xuất hóa đơn");
        btn_XuatHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XuatHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_tttLayout = new javax.swing.GroupLayout(jpn_ttt);
        jpn_ttt.setLayout(jpn_tttLayout);
        jpn_tttLayout.setHorizontalGroup(
            jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_tttLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_tttLayout.createSequentialGroup()
                        .addComponent(btn_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpn_tttLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_tttLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_TTT_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_tttLayout.createSequentialGroup()
                        .addComponent(btn_XuatHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_tttLayout.createSequentialGroup()
                        .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_TTT_GGVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpn_tttLayout.createSequentialGroup()
                                .addComponent(lbl_TTT_GGTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jpn_tttLayout.createSequentialGroup()
                        .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpn_tttLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(66, 66, 66)
                                .addComponent(lbl_TTT_TongGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpn_tttLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(107, 107, 107)
                                .addComponent(lbl_TTT_TongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jpn_tttLayout.setVerticalGroup(
            jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_tttLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_TTT_TongTien))
                .addGap(27, 27, 27)
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_TTT_GGTV))
                .addGap(29, 29, 29)
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_TTT_GGVC))
                .addGap(31, 31, 31)
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_TTT_TongGiam))
                .addGap(18, 18, 18)
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_TTT_ThanhTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpn_tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpn_uudai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_sp_mua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_ttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_uudai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img_sp_mua, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jpn_ttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_TV_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_TV_KhongActionPerformed
        // TODO add your handling code here:
        txt_TV_SDT.setEnabled(false);
        btn_CheckTV.setEnabled(false);
    }//GEN-LAST:event_rdo_TV_KhongActionPerformed

    private void rdo_TV_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_TV_CoActionPerformed
        // TODO add your handling code here:
        txt_TV_SDT.setEnabled(true);
        btn_CheckTV.setEnabled(true);
    }//GEN-LAST:event_rdo_TV_CoActionPerformed

    private void txt_TV_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TV_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TV_SDTActionPerformed

    private void txt_TV_SDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TV_SDTMouseClicked
        // TODO add your handling code here:
        if(txt_TV_SDT.getText().equals("Nhập số điện thoại...")&&txt_TV_SDT.isEnabled())
            txt_TV_SDT.setText("");
    }//GEN-LAST:event_txt_TV_SDTMouseClicked

    private void rdo_GG_KhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_GG_KhongActionPerformed
        // TODO add your handling code here:
        txt_MaGG.setEnabled(false);
        btn_CheckGG.setEnabled(false);
    }//GEN-LAST:event_rdo_GG_KhongActionPerformed

    private void rdo_GG_CoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_GG_CoActionPerformed
        // TODO add your handling code here:
        txt_MaGG.setEnabled(true);
        btn_CheckGG.setEnabled(true);
    }//GEN-LAST:event_rdo_GG_CoActionPerformed

    private void txt_MaGGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_MaGGMouseClicked
        // TODO add your handling code here:
        if(txt_MaGG.getText().equals("Nhập mã giảm giá...")&&txt_MaGG.isEnabled())
            txt_MaGG.setText("");
    }//GEN-LAST:event_txt_MaGGMouseClicked

    private void btn_CheckSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckSPActionPerformed
        // TODO add your handling code here:
        if(!txt_MaSach.getText().trim().equals(""))
        {
            DTO_Sach dtoSach = daoSach.getSach_from_MaSach(txt_MaSach.getText().trim());
            txt_TenSach.setText(dtoSach.tensach);
            txt_GiaBan.setText(dtoSach.giaban+"");
            txt_NXB.setText(dtoSach.nxb);
            txt_TacGia.setText(dtoSach.tacgia);
            txt_TheLoai.setText(dtoSach.theloai);
            if(txt_TenSach.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Mã sách không tồn tại");
                refreshChiTietSach();
            }
            else
            {
                spin_SoLuong.setValue(1);
                img_sp_mua.setIcon(new ImageIcon("E:\\CongNgheJaVa\\DoAn\\DoAn\\QuanLyBanSach\\src\\main\\resources\\Images\\"+dtoSach.hinhanh));
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền mã sách");
            refreshChiTietSach();
        }
    }//GEN-LAST:event_btn_CheckSPActionPerformed

    private void btn_freshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_freshActionPerformed
        // TODO add your handling code here:
        refreshChiTietSach();
    }//GEN-LAST:event_btn_freshActionPerformed
    private void refreshChiTietSach()
    {
        JTextField[] jtf = new JTextField[]{txt_GiaBan,txt_MaSach,txt_NXB,txt_TacGia,txt_TenSach,txt_TheLoai};
        for(JTextField i : jtf)
        {
            i.setText("");            
        }
        img_sp_mua.setIcon(new ImageIcon("E:\\CongNgheJaVa\\DoAn\\DoAn\\QuanLyBanSach\\src\\main\\resources\\Images\\loadingPic.png"));
        spin_SoLuong.setValue(1);
    }
    
    
    private void refreshChiTietUuDai()
    {
        rdo_GG_Khong.setSelected(true);
        rdo_TV_Khong.setSelected(true);
        txt_MaGG.setText("Nhập mã giảm giá...");
        txt_TV_SDT.setText("Nhập số điện thoại...");
        txt_MaGG.setEnabled(false);
        txt_TV_SDT.setEnabled(false);
        btn_CheckGG.setEnabled(false);
        btn_CheckTV.setEnabled(false);
    }
    
    private void table_QLBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_QLBanHangMouseClicked
        // TODO add your handling code here:
//        Point p = evt.getPoint();
//        int row = table_QLBanHang.rowAtPoint(p);
//        String  masach= (String)modelDS.getValueAt(row, 1).toString();
//        String  soluong= (String)modelDS.getValueAt(row, 6).toString();
//        String  tongtien= (String)modelDS.getValueAt(row, 7).toString();
//        String tonggiam= (String)modelDS.getValueAt(row, 8).toString();
//        String thanhtien= (String)modelDS.getValueAt(row, 9).toString();
//        String pathAnh = _dao.getHinhAnh_from_MaSach(masach);
//        
//        lbl_TTT_TenSP.setText(_dao.getTenSach_from_MaSach(masach));
//        lbl_TTT_SL.setText(soluong);
//        lbl_TTT_DonGia.setText(String.valueOf(Integer.parseInt(tongtien)/Integer.parseInt(soluong)));
//        lbl_TTT_ThanhTien.setText(thanhtien);
//        lbl_TTT_TongGiam.setText(tonggiam);
//        lbl_TTT_TongTien.setText(tongtien);
//        img_sp_mua.setIcon(new ImageIcon("E:\\CongNgheJaVa\\DoAn\\DoAn\\QuanLyBanSach\\src\\main\\resources\\Images\\"+pathAnh));
    }//GEN-LAST:event_table_QLBanHangMouseClicked

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
        LocalDate currentdate = LocalDate.now();
        int d = JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán: "+lbl_TTT_ThanhTien.getText(),"Thoát",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(d==JOptionPane.YES_OPTION)
        {
            //Tạo hoa don ban
            int maTV = 1;
            if(!lbl_TTT_GGTV.getText().equals("0"))
            {
                maTV = Integer.parseInt(daoTV.getMaTV_from_SDT(txt_TV_SDT.getText().trim()));
            }
            String maGG = "None";
            if(!lbl_TTT_GGVC.getText().equals("0"))
            {
                maGG = txt_MaGG.getText().trim();
            }
            
            DTO_HoaDonBan x = new DTO_HoaDonBan(
                    "X",
                    currentdate.getMonthValue()+"/"+currentdate.getDayOfMonth()+"/"+currentdate.getYear(),
                    Integer.parseInt(lbl_TTT_TongTien.getText()),
                    Integer.parseInt(lbl_TTT_TongGiam.getText()),
                    Integer.parseInt(lbl_TTT_ThanhTien.getText()),
                    maTV+"", maGG, maTK
            );
//            
            if(daoSach.addHoaDonBan(x))
            {
                //Tạo cthd
                
                for(DTO_ChiTietHoaDon i : lstCTHD)
                {
                    daoSach.addChiTietHDB(i, daoHDB.getHoaDonBanMoiNhat());
                }
                
                //Trừ số lượng tồn
                for(DTO_ChiTietHoaDon i : lstCTHD)
                {
                    daoSach.updateSoLuongTon(i);
                }
                
                //Cập nhật tiền mua hàng 
                if(maTV!=1)
                {
                    daoTV.updateTienDaMua(maTV, Integer.parseInt(lbl_TTT_ThanhTien.getText()));
                }
                JOptionPane.showMessageDialog(this, "Lưu bán hàng thành công");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu");
            }
            refreshChiTietSach();refreshChiTietUuDai();refreshTongThanhToan();            
        }
        
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void spin_SoLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spin_SoLuongMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spin_SoLuongMouseClicked

    private void spin_SoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spin_SoLuongKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spin_SoLuongKeyTyped

    private void spin_SoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spin_SoLuongKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_spin_SoLuongKeyPressed

    private void spin_SoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spin_SoLuongKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spin_SoLuongKeyReleased

    private void spin_SoLuongHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_spin_SoLuongHierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spin_SoLuongHierarchyChanged

    private void spin_SoLuongInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_spin_SoLuongInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spin_SoLuongInputMethodTextChanged

    private void spin_SoLuongAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spin_SoLuongAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_spin_SoLuongAncestorAdded

    private void spin_SoLuongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spin_SoLuongMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_spin_SoLuongMousePressed

    private void spin_SoLuongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spin_SoLuongMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_spin_SoLuongMouseExited

    private void spin_SoLuongVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_spin_SoLuongVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spin_SoLuongVetoableChange

    private void spin_SoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_SoLuongStateChanged
        // TODO add your handling code here:
        if(Integer.parseInt(String.valueOf(spin_SoLuong.getValue())) <1)
        {
            JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0", "Lỗi", JOptionPane.YES_OPTION);
            spin_SoLuong.setValue(1);
        }
    }//GEN-LAST:event_spin_SoLuongStateChanged

    private void btn_CheckTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckTVActionPerformed
        // TODO add your handling code here:
        if(txt_TV_SDT.getText().equals("")||txt_TV_SDT.getText().equals("Nhập số điện thoại..."))
            JOptionPane.showMessageDialog(this, "Chưa nhập thông tin thành viên", "Thông báo", JOptionPane.OK_OPTION);
        else
        {
            if(DAO_ThanhVien.checkValidMembers(txt_TV_SDT.getText().trim()))
            {
                DTO_ThanhVien tv = DAO_ThanhVien.getThanhVien_from_SDT(txt_TV_SDT.getText().trim());
                JOptionPane.showMessageDialog(this, "Phần trăm giảm của thành viên: "+String.valueOf(DAO_ThanhVien.getMoneyOffer_from_SDT(txt_TV_SDT.getText().trim())) + "%", "Thông báo", JOptionPane.OK_OPTION);
                ggTV = DAO_ThanhVien.getMoneyOffer_from_SDT(txt_TV_SDT.getText().trim())*Integer.parseInt(lbl_TTT_TongTien.getText().trim())/100;
                lbl_TTT_GGTV.setText(""+ggTV);
                lbl_TTT_TongGiam.setText(""+(ggTV+ggVC));
                lbl_TTT_ThanhTien.setText(""+ (tongtien - ggTV - ggVC));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thành viên không tồn tại", "Thông báo", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_btn_CheckTVActionPerformed

    private void txt_TV_SDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TV_SDTKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9'||evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_TV_SDTKeyTyped

    private void btn_CheckGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckGGActionPerformed
        // TODO add your handling code here:
        if(txt_MaGG.getText().equals("")||txt_MaGG.getText().equals("Nhập mã giảm giá..."))
            JOptionPane.showMessageDialog(this, "Chưa nhập thông tin mã giảm giá", "Thông báo", JOptionPane.OK_OPTION);
        else
        {
            if(DAO_PhieuGG.checkValidVouchers(txt_MaGG.getText().trim()))
            {
                if(DAO_PhieuGG.isDuringSale(txt_MaGG.getText().trim()))
                {
                DTO_PhieuGG tv = DAO_PhieuGG.getPhieuGG_from_MaGG(txt_MaGG.getText().trim());
                JOptionPane.showMessageDialog(this, "Phần trăm giảm của Voucher: "+String.valueOf(DAO_PhieuGG.getMoneyOffer_from_MaGG(txt_MaGG.getText().trim())) + "%", "Thông báo", JOptionPane.OK_OPTION);
                ggVC = DAO_PhieuGG.getMoneyOffer_from_MaGG(txt_MaGG.getText().trim())*Integer.parseInt(lbl_TTT_TongTien.getText().trim())/100;
                lbl_TTT_GGVC.setText(""+ggVC);
                lbl_TTT_TongGiam.setText(""+(ggTV+ggVC));
                lbl_TTT_ThanhTien.setText(""+ (tongtien - ggTV - ggVC));
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Mã giảm giá không trong thời gian khuyến mãi", "Thông báo", JOptionPane.OK_OPTION);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Mã giảm giá không tồn tại", "Thông báo", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_btn_CheckGGActionPerformed
    
    private void txt_MaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaSachActionPerformed
    
    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        refreshChiTietSach();refreshChiTietUuDai();refreshTongThanhToan();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_AddToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddToListActionPerformed
        // TODO add your handling code here:
        LocalDate currentdate = LocalDate.now();
        if(!txt_TenSach.getText().trim().equals(""))
        {
            if(daoSach.checkSLTonDu(txt_MaSach.getText().trim(), Integer.parseInt(String.valueOf(spin_SoLuong.getValue()))))
            {
                if(!checkDaCoTrongArrayyList(txt_MaSach.getText().trim()))
                {
                lstCTHD.add(new DTO_ChiTietHoaDon(
                        txt_MaSach.getText().trim(),
                        txt_TenSach.getText().trim(),
                        currentdate.getDayOfMonth()+"/"+currentdate.getMonthValue()+"/"+currentdate.getYear(),
                        maTK, Integer.parseInt(txt_GiaBan.getText().trim()), Integer.parseInt(String.valueOf(spin_SoLuong.getValue())),
                        Integer.parseInt(txt_GiaBan.getText().trim())*Integer.parseInt(String.valueOf(spin_SoLuong.getValue()))
                ));
                }
                else
                {
                    //Cập nhật số lượng thôi                    
                    lstCTHD.add(new DTO_ChiTietHoaDon(
                        txt_MaSach.getText().trim(),
                        txt_TenSach.getText().trim(),
                        currentdate.getDayOfMonth()+"/"+currentdate.getMonthValue()+"/"+currentdate.getYear(),
                        maTK, Integer.parseInt(txt_GiaBan.getText().trim()), Integer.parseInt(String.valueOf(spin_SoLuong.getValue()))+getSLTTrongArrayyList(txt_MaSach.getText().trim()),
                        Integer.parseInt(txt_GiaBan.getText().trim())*(+getSLTTrongArrayyList(txt_MaSach.getText().trim())+Integer.parseInt(String.valueOf(spin_SoLuong.getValue())))
                    ));
                    lstCTHD.remove(getViTriTrongArrayyList(txt_MaSach.getText().trim()));
                }
                
                loadListCTHD();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Số lượng tồn không đủ");
            }
        }
        
    }//GEN-LAST:event_btn_AddToListActionPerformed

    public boolean checkDaCoTrongArrayyList(String masach)
    {
        for(DTO_ChiTietHoaDon i : lstCTHD)
            if(i.masach.equals(masach))
                return true;
        return false;
    }
    
    public int getViTriTrongArrayyList(String masach)
    {
        int vt = 0;
        for(DTO_ChiTietHoaDon i : lstCTHD)
        {
            if(i.masach.equals(masach))
                return vt;
            vt+=1;
        }
        return vt;
    }
    
    public int getSLTTrongArrayyList(String masach)
    {
        int vt = 0;
        for(DTO_ChiTietHoaDon i : lstCTHD)
        {
            if(i.masach.equals(masach))
                return i.soluong;
        }
        return vt;
    }
    
    private void btn_RemoveAllListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveAllListActionPerformed
        // TODO add your handling code here:
        lstCTHD = new ArrayList<DTO_ChiTietHoaDon>();
        loadListCTHD();
    }//GEN-LAST:event_btn_RemoveAllListActionPerformed

    private void btn_XuatHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatHDActionPerformed
        // TODO add your handling code here:
  
    int id=daoHDB.getHoaDonBanMoiNhat();
    
        
          try
    {
        Hashtable map = new Hashtable();
        JasperReport rp=JasperCompileManager.compileReport("src/main/java/REPORT/rp_QLHoaDon.jrxml");
        map.put("SoHD", id);
        DBConnection cn  = new DBConnection();
        JasperPrint print = JasperFillManager.fillReport(rp, map, cn.getCn());
        JasperViewer.viewReport(print,false);
        
        }
       catch(JRException ex)
        {
            Logger.getLogger(penel_QLHoaDon.class.getName()).log(Level.SEVERE,null,ex);
        }
    
    }//GEN-LAST:event_btn_XuatHDActionPerformed

    public void loadListCTHD()
    {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(title);
        table_QLBanHang.setModel(model);
        tongtien =0;
        for(DTO_ChiTietHoaDon i : lstCTHD)
        {
            Vector a = new Vector();
            a.add(i.masach); a.add(i.tensach);a.add(i.ngaylap);a.add(i.nguoilap);a.add(i.giaban);a.add(i.soluong);a.add(i.tongtien);
            model.addRow(a);
            tongtien+=i.tongtien;
        }
        lbl_TTT_TongTien.setText(""+tongtien);
        lbl_TTT_GGTV.setText(""+ggTV);
        lbl_TTT_GGVC.setText(""+ggVC);
        lbl_TTT_TongGiam.setText(""+(ggTV+ggVC));
        lbl_TTT_ThanhTien.setText(""+ (tongtien - ggTV - ggVC));
    }
    
    public void refreshTongThanhToan()
    {
        lbl_TTT_GGTV.setText("0");
        lbl_TTT_GGVC.setText("0");
        lbl_TTT_TongTien.setText("0");
        lbl_TTT_TongGiam.setText("0");
        lbl_TTT_ThanhTien.setText("0");
        
        tongtien = ggTV = ggVC = 0;
        lstCTHD = new ArrayList<DTO_ChiTietHoaDon>();
        loadListCTHD();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddToList;
    private javax.swing.JButton btn_CheckGG;
    private javax.swing.JButton btn_CheckSP;
    private javax.swing.JButton btn_CheckTV;
    private javax.swing.JButton btn_RemoveAllList;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_XuatHD;
    private javax.swing.JButton btn_fresh;
    private javax.swing.ButtonGroup btngroup_BanSachMaGG;
    private javax.swing.ButtonGroup btngroup_BanSachThanhVien;
    private javax.swing.JLabel img_sp_mua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpn_ttt;
    private javax.swing.JPanel jpn_uudai;
    private javax.swing.JLabel lbl_TTT_GGTV;
    private javax.swing.JLabel lbl_TTT_GGVC;
    private javax.swing.JLabel lbl_TTT_ThanhTien;
    private javax.swing.JLabel lbl_TTT_TongGiam;
    private javax.swing.JLabel lbl_TTT_TongTien;
    private javax.swing.JRadioButton rdo_GG_Co;
    private javax.swing.JRadioButton rdo_GG_Khong;
    private javax.swing.JRadioButton rdo_TV_Co;
    private javax.swing.JRadioButton rdo_TV_Khong;
    private javax.swing.JSpinner spin_SoLuong;
    private javax.swing.JTable table_QLBanHang;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_MaGG;
    private javax.swing.JTextField txt_MaSach;
    private javax.swing.JTextField txt_NXB;
    private javax.swing.JTextField txt_TV_SDT;
    private javax.swing.JTextField txt_TacGia;
    private javax.swing.JTextField txt_TenSach;
    private javax.swing.JTextField txt_TheLoai;
    // End of variables declaration//GEN-END:variables

}
