package GUI;

import DAO.DAO_HoaDonBan;
import DAO.DAO_KeDat;
import DAO.DAO_NXB;
import DAO.DAO_Sach;
import DTO.DTO_Sach;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import javax.swing.ImageIcon;
import DAO.DBConnection;
import DAO.DAO_SanPham;
import DAO.DAO_Tang;
import DAO.DAO_TheLoai;
import DTO.DTO_HoaDonBan;
import DTO.DTO_KeDat;
import DTO.DTO_NXB;
import DTO.DTO_SanPham;
import DTO.DTO_Tang;
import DTO.DTO_TheLoai;
import java.awt.Dimension;
import java.awt.Point;
import java.net.FileNameMap;
import java.net.URLConnection;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ChauCuteVCL
 */
public class panel_QLSanPham extends javax.swing.JPanel {
    
    DAO_SanPham _dao = new DAO_SanPham();
    DefaultTableModel modelDS = new DefaultTableModel();
    Vector data = new Vector();
     Vector tblTitle = new Vector();
    String path="";
    /**
     * Creates new form panel_QLSanPham
     */
    public panel_QLSanPham() {
        initComponents();
        loadTitle();
        loadDS();
        loadDS_NXB();
        loadDS_TL();
        loadDS_Tang();
        loadDS_Ke();
        VisibleButton_LuuHuy(false, btn_LamMoi);
    }
    public void loadTitle(){
       
        tblTitle.add("Mã sách");
        tblTitle.add("Tên sách"); 
        tblTitle.add("Tác giả");
        tblTitle.add("Số trang"); 
        tblTitle.add("Giá bán");
        tblTitle.add("Số lượng tồn"); 
        tblTitle.add("Mã thể loại");
        tblTitle.add("Mã NXB"); 
        tblTitle.add("Mã tầng");
        tblTitle.add("Mã kệ");  
    }
   public void loadDS()
    {
       data = new Vector();
       modelDS = new DefaultTableModel();
       modelDS.setColumnIdentifiers(tblTitle);
       List<DTO_SanPham> lst = _dao.getDS_Sach();
        for(DTO_SanPham i : lst)
        {
            Vector a = new Vector();
            a.add(i.MaSach);
            a.add(i.TenSach);
            a.add(i.TacGia);
            a.add(i.SoTrang);
            a.add(i.GiaBan);
            a.add(i.SoLuongTon);
            a.add(i.MaTheLoai);
            a.add(i.MaNXB);
            a.add(i.MaTang);
            a.add(i.MaKe);
            data.add(a);
            modelDS.addRow(a);
        }
        
        table_QLSP.setModel(new DefaultTableModel( data,tblTitle));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_sp_mua = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_QLSP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_MaSach = new javax.swing.JTextField();
        txt_TenSach = new javax.swing.JTextField();
        txt_TacGia = new javax.swing.JTextField();
        txt_GiaBan = new javax.swing.JTextField();
        btn_CheckSP = new javax.swing.JButton();
        cbb_NXB = new javax.swing.JComboBox<>();
        cbb_TheLoai = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txt_SoTrang = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cbb_KeDat = new javax.swing.JComboBox<>();
        cbb_Tang = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        btn_ChooseFile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_ThemSP = new javax.swing.JButton();
        btn_SuaSP = new javax.swing.JButton();
        btn_XoaSP = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_BoChon = new javax.swing.JButton();
        btn_Luu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        img_sp_mua.setBackground(new java.awt.Color(255, 153, 102));
        img_sp_mua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loadingPic.png"))); // NOI18N
        img_sp_mua.setName(""); // NOI18N

        table_QLSP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_QLSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_QLSP.setRowHeight(35);
        table_QLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_QLSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_QLSP);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Thông tin sản phẩm:");
        jLabel3.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Mã sách:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Tên sách:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Tác giả:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Thể loại:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("NXB:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Giá bán:");

        txt_MaSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TenSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_GiaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_GiaBanKeyTyped(evt);
            }
        });

        btn_CheckSP.setBackground(new java.awt.Color(102, 153, 255));
        btn_CheckSP.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_CheckSP.setText("Kiểm tra");
        btn_CheckSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_CheckSP.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_CheckSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckSPActionPerformed(evt);
            }
        });

        cbb_NXB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_NXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_NXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_NXBActionPerformed(evt);
            }
        });

        cbb_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_TheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_TheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_TheLoaiActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Số trang:");

        txt_SoTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_SoTrang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SoTrangKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Tầng:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Kệ đặt:");

        cbb_KeDat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_KeDat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbb_Tang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbb_Tang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Ảnh:");

        btn_ChooseFile.setBackground(new java.awt.Color(249, 249, 249));
        btn_ChooseFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ChooseFile.setText("Chọn ảnh...");
        btn_ChooseFile.setToolTipText("");
        btn_ChooseFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_ChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChooseFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_CheckSP))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel26))
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_GiaBan)
                                                    .addComponent(btn_ChooseFile, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addGap(47, 47, 47)
                                                .addComponent(cbb_Tang, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                        .addComponent(jLabel25)
                                        .addGap(41, 41, 41)
                                        .addComponent(cbb_KeDat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbb_TheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_SoTrang)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_TenSach)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_MaSach)
                                        .addGap(143, 143, 143))
                                    .addComponent(txt_TacGia)
                                    .addComponent(cbb_NXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btn_CheckSP))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_TenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_NXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_SoTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(cbb_KeDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_Tang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(btn_ChooseFile))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Thao tác nghiệp vụ:");
        jLabel4.setToolTipText("");

        btn_ThemSP.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_ThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/library.png"))); // NOI18N
        btn_ThemSP.setText("Thêm sản phẩm");
        btn_ThemSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSPActionPerformed(evt);
            }
        });

        btn_SuaSP.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_SuaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/phonebook.png"))); // NOI18N
        btn_SuaSP.setText("Sửa sản phẩm");
        btn_SuaSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaSPActionPerformed(evt);
            }
        });

        btn_XoaSP.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_XoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/noChoose.png"))); // NOI18N
        btn_XoaSP.setText("Xóa sản phẩm");
        btn_XoaSP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_XoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaSPActionPerformed(evt);
            }
        });

        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_LamMoi.setText("     Làm mới");
        btn_LamMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_BoChon.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_BoChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/negative.png"))); // NOI18N
        btn_BoChon.setText(" Hủy thay đổi");
        btn_BoChon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_BoChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BoChonActionPerformed(evt);
            }
        });

        btn_Luu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_Luu.setText("Lưu thông tin");
        btn_Luu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BoChon, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(btn_ThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_BoChon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img_sp_mua, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_sp_mua, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser jfile = new JFileChooser();
        FileNameExtensionFilter fileExten = new FileNameExtensionFilter("Chọn hình ảnh", "png", "jpg");
        jfile.setFileFilter(fileExten);
        jfile.setMultiSelectionEnabled(false);
        
        if(jfile.showDialog(this, "Chọn hình ảnh")==JFileChooser.APPROVE_OPTION)
        {
            File f = jfile.getSelectedFile();
            FileNameMap fnameMap = URLConnection.getFileNameMap();
            String mt = fnameMap.getContentTypeFor(f.getName());
            System.out.println(mt);
            if(mt==null)
            {
                JOptionPane.showMessageDialog(this, "Sai mã");
                return;
            }
            else
            {
                path = f.getName();
                img_sp_mua.setIcon(new ImageIcon(f.getAbsolutePath()));
            }
            
        }
        
    }//GEN-LAST:event_btn_ChooseFileActionPerformed

    private void btn_CheckSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckSPActionPerformed
        // TODO add your handling code here:
        if(txt_MaSach.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Hãy điền thông tin mã sách!","Thông báo",JOptionPane.YES_OPTION);
        }
        else{
            if(!txt_MaSach.getText().trim().equals(""))
            {
                DTO_SanPham _sach = _dao.getSachfromMa(txt_MaSach.getText().trim());
                    txt_GiaBan.setText(String.valueOf(_sach.GiaBan));
                    cbb_NXB.setSelectedItem(_dao.getTenNXB(txt_MaSach.getText().trim()));
                    txt_TacGia.setText(_sach.TacGia);
                    txt_TenSach.setText(_sach.TenSach);
                    cbb_TheLoai.setSelectedItem(_dao.getTenTheLoaiSach(txt_MaSach.getText().trim()));
                    txt_SoTrang.setText(String.valueOf(_sach.SoTrang));
                    cbb_KeDat.setSelectedItem(_dao.getTenKe(_sach.MaKe));
                    cbb_Tang.setSelectedItem(_dao.getTenTang(_sach.MaTang));
                if(txt_TenSach.getText().trim().equals(""))
                {
                    JOptionPane.showMessageDialog(this, "Mã sách không tồn tại!","Thông báo",JOptionPane.YES_OPTION);                    
                }
                else
                {
                    img_sp_mua.setIcon(new ImageIcon("E:\\CongNgheJaVa\\DoAn\\DoAn\\QuanLyBanSach\\src\\main\\resources\\Images\\"+_sach.HinhAnh));
                }
            }
        }
    }//GEN-LAST:event_btn_CheckSPActionPerformed

    private void cbb_NXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_NXBActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cbb_NXBActionPerformed

    private void table_QLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_QLSPMouseClicked
        // TODO add your handling code here:
        Point p = evt.getPoint();
        int row = table_QLSP.rowAtPoint(p);
        String masach = (String)modelDS.getValueAt(row, 0).toString();
        String tensach = (String)modelDS.getValueAt(row, 1).toString();
        String tacgia = (String)modelDS.getValueAt(row, 2).toString();
        String sotrang = (String)modelDS.getValueAt(row, 3).toString();
        String giaban=(String)modelDS.getValueAt(row, 4).toString();
        String maNXB=(String)modelDS.getValueAt(row, 7).toString();
        String maTL=(String)modelDS.getValueAt(row, 6).toString();
        String matang=(String)modelDS.getValueAt(row, 8).toString();
        String make=(String)modelDS.getValueAt(row, 9).toString();
        String pathAnh = _dao.getSachfromMa(masach).HinhAnh;
        path = pathAnh;
        
        txt_MaSach.setText(masach);
        txt_TenSach.setText(tensach);
        txt_TacGia.setText(tacgia);
        txt_SoTrang.setText(sotrang);
        txt_GiaBan.setText(giaban);
        cbb_TheLoai.setSelectedItem(DAO_TheLoai.getTen_from_Ma(maTL));
        cbb_NXB.setSelectedItem(DAO_NXB.getTen_from_Ma(maNXB));
        cbb_KeDat.setSelectedItem(DAO_KeDat.getTen_from_Ma(make));
        cbb_Tang.setSelectedItem(DAO_Tang.getTen_from_Ma(matang));
        img_sp_mua.setIcon(new ImageIcon("E:\\CongNgheJaVa\\DoAn\\DoAn\\QuanLyBanSach\\src\\main\\resources\\Images\\"+pathAnh));
       
    }//GEN-LAST:event_table_QLSPMouseClicked

    private void btn_ThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSPActionPerformed
        // TODO add your handling code here:  
        
        if(checkFullInformation()&&!path.equals(""))
        {
            if(!_dao.checkExistPrimarykey(txt_MaSach.getText().trim()))
            {
                VisibleButton_LuuHuy(true, btn_ThemSP);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã sách đã tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_ThemSPActionPerformed

    private void cbb_TheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_TheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_TheLoaiActionPerformed

    private void btn_BoChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BoChonActionPerformed
        // TODO add your handling code here:
        VisibleButton_LuuHuy(false,btn_LamMoi);
        path ="";
    }//GEN-LAST:event_btn_BoChonActionPerformed

    private void btn_SuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaSPActionPerformed
        // TODO add your handling code here:
        
       if(checkFullInformation()&&!path.equals(""))
        {
            if(_dao.checkExistPrimarykey(txt_MaSach.getText().trim()))
            {
                VisibleButton_LuuHuy(true, btn_SuaSP);
            }
            else
                JOptionPane.showMessageDialog(this, "Mã sách đang sửa không tồn tại!","Thông báo",JOptionPane.YES_OPTION);
        }
        else
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!","Thông báo",JOptionPane.YES_OPTION);
    }//GEN-LAST:event_btn_SuaSPActionPerformed

    private void btn_XoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaSPActionPerformed
        // TODO add your handling code here:
        if(!_dao.checkExistForeignkey(txt_MaSach.getText().trim()))
            VisibleButton_LuuHuy(true, btn_XoaSP);
        else
        {
            JOptionPane.showMessageDialog(this, "Sách đang giữ khóa ngoại, không thể xóa!","Thông báo",JOptionPane.YES_OPTION);
        }
    }//GEN-LAST:event_btn_XoaSPActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        // TODO add your handling code here:
        //VisibleButton_LuuHuy(false, btn_LamMoi);
        if(btn_ThemSP.isEnabled())
        {
            //Thêm
            DTO_SanPham sp = new DTO_SanPham(txt_MaSach.getText().trim(),txt_TenSach.getText(),txt_TacGia.getText(),
                
                _dao.getMaTheLoai(cbb_TheLoai.getSelectedItem().toString()),
                    _dao.getMaNXB(cbb_NXB.getSelectedItem().toString()),
                _dao.getMaTang(cbb_Tang.getSelectedItem().toString()),
                _dao.getMaKe(cbb_KeDat.getSelectedItem().toString()),
                    path,
                    Integer.parseInt(txt_SoTrang.getText().trim()),
                    Integer.parseInt(txt_GiaBan.getText().trim()),
                    0
            );
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_dao.addSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm mới thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, thêm thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            
        }
        else if(btn_XoaSP.isEnabled())
        {
            if(_dao.delSanPham(txt_MaSach.getText().trim()))
            {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sản phẩm đang giữ khóa ngoại, xóa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
            //Xóa
        }
        else if(btn_SuaSP.isEnabled())
        {
           DTO_SanPham sp = new DTO_SanPham(txt_MaSach.getText().trim(),txt_TenSach.getText(),txt_TacGia.getText(),
                
                _dao.getMaTheLoai(cbb_TheLoai.getSelectedItem().toString()),
                    _dao.getMaNXB(cbb_NXB.getSelectedItem().toString()),
                _dao.getMaTang(cbb_Tang.getSelectedItem().toString()),
                _dao.getMaKe(cbb_KeDat.getSelectedItem().toString()),
                    path,
                    Integer.parseInt(txt_SoTrang.getText().trim()),
                    Integer.parseInt(txt_GiaBan.getText().trim()),
                    0
            );
            //System.out.println(sp.MaSach+"',N'"+sp.TenSach+"',N'"+sp.TacGia+"',"+String.valueOf(sp.SoTrang)+","+String.valueOf(sp.GiaBan)+","+String.valueOf(sp.SoLuongTon)+",'"+sp.MaTheLoai+"','"+sp.MaNXB+"','"+sp.MaTang+"','"+sp.MaKe+"',N'"+sp.HinhAnh);
            if(_dao.updateSanPham(sp))
            {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!","Thông báo",JOptionPane.YES_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu, sửa thất bại!","Thông báo",JOptionPane.YES_OPTION);
            }
        }
        loadDS();
         VisibleButton_LuuHuy(false, btn_LamMoi);
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        path ="";
        JTextField[] ds = new JTextField[]{txt_MaSach,txt_GiaBan,txt_SoTrang,txt_TacGia,txt_TenSach};
        for(JTextField i : ds)
            i.setText("");
        VisibleButton_LuuHuy(false, btn_LamMoi);
        JComboBox[] cbb = new JComboBox[]{cbb_KeDat,cbb_NXB,cbb_Tang,cbb_TheLoai};
        for(JComboBox i : cbb)
        {
            i.setSelectedIndex(0);
        }
        img_sp_mua.setIcon(new ImageIcon("E:\\CongNgheJaVa\\DoAn\\DoAn\\QuanLyBanSach\\src\\main\\resources\\Images\\loadingPic.png"));
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void txt_SoTrangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoTrangKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_SoTrangKeyTyped

    private void txt_GiaBanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_GiaBanKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()>'9' || evt.getKeyChar()<'0') evt.consume();
    }//GEN-LAST:event_txt_GiaBanKeyTyped

    public void loadDS_NXB()
    {
        ArrayList<DTO_NXB> cbb = DAO_NXB.listNXB();
         cbb_NXB.removeAllItems();
        for(DTO_NXB i : cbb)
        {
            cbb_NXB.addItem(i.TenNXB);
        }
    }
    public void loadDS_Tang()
    {
        ArrayList<DTO_Tang> cbb = DAO_Tang.listTang();
         cbb_Tang.removeAllItems();
        for(DTO_Tang i : cbb)
        {
            cbb_Tang.addItem(i.TenTang);
        }
    }
    public void loadDS_Ke()
    {
        ArrayList<DTO_KeDat> cbb = DAO_KeDat.listKeDat();
         cbb_KeDat.removeAllItems();
        for(DTO_KeDat i : cbb)
        {
            cbb_KeDat.addItem(i.TenKe);
        }
    }
    public void loadDS_TL()
    {
        ArrayList<DTO_TheLoai> cbb = DAO_TheLoai.listTheLoai();
         cbb_TheLoai.removeAllItems();
        for(DTO_TheLoai i : cbb)
        {
            cbb_TheLoai.addItem(i.TenTheLoai);
        }
    }

    private void VisibleButton_LuuHuy(boolean bool, JButton btn)
    {
        if(bool)
        {
            JButton[] ds = new JButton[]{btn_BoChon,btn_Luu};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
            ds = new JButton[]{btn_ThemSP,btn_XoaSP,btn_SuaSP};
            for(JButton i : ds)
            {
                if(i!=btn)
                    i.setEnabled(false);
            }
        }
        else
        {
            JButton[] ds = new JButton[]{btn_BoChon,btn_Luu};
            for(JButton i : ds)
            {
                i.setEnabled(false);
            }
            ds = new JButton[]{btn_ThemSP,btn_XoaSP,btn_SuaSP};
            for(JButton i : ds)
            {
                i.setEnabled(true);
            }
        }
    }
    
    private boolean checkFullInformation()
    {
        JTextField[] ds = new JTextField[]{txt_MaSach,txt_GiaBan,txt_SoTrang,txt_TacGia,txt_TenSach};
        for(JTextField i : ds)
            if(i.getText().trim().equals(""))
                return false;
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BoChon;
    private javax.swing.JButton btn_CheckSP;
    private javax.swing.JButton btn_ChooseFile;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_SuaSP;
    private javax.swing.JButton btn_ThemSP;
    private javax.swing.JButton btn_XoaSP;
    private javax.swing.JComboBox<String> cbb_KeDat;
    private javax.swing.JComboBox<String> cbb_NXB;
    private javax.swing.JComboBox<String> cbb_Tang;
    private javax.swing.JComboBox<String> cbb_TheLoai;
    private javax.swing.JLabel img_sp_mua;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_QLSP;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_MaSach;
    private javax.swing.JTextField txt_SoTrang;
    private javax.swing.JTextField txt_TacGia;
    private javax.swing.JTextField txt_TenSach;
    // End of variables declaration//GEN-END:variables

   

}
